repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff-format
        files: ^analytics
        types_or: [python]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.2.5
    hooks:
      - id: sqlfluff-fix
        files: ^analytics
        types: [sql]
        additional_dependencies:
          - sqlfluff-templater-dbt==3.2.5
          - dbt-postgres==1.8.2
