# Generated by Django 6.0.2 on 2026-03-02 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessions.session",
                        verbose_name="session Django",
                    ),
                ),
            ],
            options={
                "verbose_name": "sessions pour un utilisateur",
                "verbose_name_plural": "sessions pour un utilisateur",
            },
        ),
    ]
