# Generated by Django 5.2.6 on 2025-10-08 15:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        help_text="Type d'import (services, structures, etc.)",
                        max_length=50,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "current_row",
                    models.IntegerField(
                        default=0, help_text="Ligne en cours de traitement"
                    ),
                ),
                (
                    "total_rows",
                    models.IntegerField(default=0, help_text="Nombre total de lignes"),
                ),
                (
                    "result_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Résultats de l'import"
                    ),
                ),
                (
                    "messages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Messages formatés pour affichage",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Message d'erreur si échec"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_import_user_id_fd8de9_idx",
                    ),
                    models.Index(
                        fields=["status"], name="core_import_status_f88dda_idx"
                    ),
                ],
            },
        ),
    ]
