# Generated by Django 5.2.9 on 2026-01-15 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_importjob"),
        ("orientations", "0020_orientation_is_anonymized"),
    ]

    operations = [
        migrations.AddField(
            model_name="logitem",
            name="orientation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orientations.orientation",
            ),
        ),
    ]
