# Generated by Django 6.0.2 on 2026-03-02 14:46

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "code",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=230)),
                ("normalized_name", models.CharField(max_length=230)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        geography=True, srid=4326
                    ),
                ),
                ("department", models.CharField(db_index=True, max_length=3)),
                ("region", models.CharField(db_index=True, max_length=2)),
                ("epci", models.CharField(db_index=True, max_length=20)),
                (
                    "epcis",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=9, primary_key=True),
                        blank=True,
                        default=list,
                    ),
                ),
                ("population", models.IntegerField()),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["normalized_name"],
                        name="city_name_trgm_idx",
                        opclasses=("gin_trgm_ops",),
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "code",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=230)),
                ("normalized_name", models.CharField(max_length=230)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        geography=True, srid=4326
                    ),
                ),
                ("region", models.CharField(db_index=True, max_length=2)),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["normalized_name"],
                        name="department_name_trgm_idx",
                        opclasses=("gin_trgm_ops",),
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EPCI",
            fields=[
                (
                    "code",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=230)),
                ("normalized_name", models.CharField(max_length=230)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        geography=True, srid=4326
                    ),
                ),
                ("nature", models.CharField(db_index=True, max_length=150)),
                (
                    "departments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=9, primary_key=True),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "regions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=9, primary_key=True),
                        blank=True,
                        default=list,
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["normalized_name"],
                        name="epci_name_trgm_idx",
                        opclasses=("gin_trgm_ops",),
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "code",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=230)),
                ("normalized_name", models.CharField(max_length=230)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        geography=True, srid=4326
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["normalized_name"],
                        name="region_name_trgm_idx",
                        opclasses=("gin_trgm_ops",),
                    )
                ],
            },
        ),
    ]
