# Generated by Django 6.0.2 on 2026-03-02 14:46

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import itoutils.django.nexus.models
from django.conf import settings
from django.db import migrations, models

import dora.core.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisabledDoraFormDIStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=255, verbose_name="Source")),
                (
                    "structure_id",
                    models.CharField(
                        max_length=1024, verbose_name="ID de la structure"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Commentaire")),
            ],
            options={
                "verbose_name": "structure DI avec formulaire Dora désactivé",
                "verbose_name_plural": "structures DI avec formulaire Dora désactivé",
            },
        ),
        migrations.CreateModel(
            name="StructureNationalLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Label national",
                "verbose_name_plural": "Labels nationaux",
            },
        ),
        migrations.CreateModel(
            name="StructureSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Source",
            },
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "moderation_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "NEED_INITIAL_MODERATION",
                                "Première modération nécessaire",
                            ),
                            ("NEED_NEW_MODERATION", "Nouvelle modération nécessaire"),
                            ("IN_PROGRESS", "En cours"),
                            ("VALIDATED", "Validé"),
                        ],
                        db_index=True,
                        max_length=30,
                        null=True,
                        verbose_name="Modération",
                    ),
                ),
                ("moderation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        unique=True,
                        validators=[dora.core.validators.validate_siret],
                        verbose_name="SIRET",
                    ),
                ),
                (
                    "code_safir_ft",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=5,
                        null=True,
                        unique=True,
                        validators=[dora.core.validators.validate_safir],
                        verbose_name="code SAFIR France Travail",
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=255, verbose_name="Nom"),
                ),
                (
                    "typology",
                    models.CharField(
                        choices=[
                            (
                                "ACI",
                                "Structures porteuses d’ateliers et chantiers d’insertion (ACI)",
                            ),
                            (
                                "ACIPHC",
                                "SIAE — Atelier chantier d’insertion premières heures en chantier",
                            ),
                            (
                                "AFPA",
                                "Agence nationale pour la formation professionnelle des adultes (AFPA)",
                            ),
                            ("AI", "Associations intermédiaires (AI)"),
                            ("ASE", "Aide sociale à l’enfance (ASE)"),
                            ("ASSO", "Associations"),
                            ("ASSO_CHOMEUR", "Associations de chômeurs"),
                            ("Autre", "Autre"),
                            (
                                "AVIP",
                                "Crèche À Vocation d’Insertion Professionnelle (AVIP)",
                            ),
                            ("BIB", "Bibliothèque / Médiathèque"),
                            (
                                "CAARUD",
                                "CAARUD - Centre d’accueil et d’accompagnement à la réduction de risques pour usagers de drogues",
                            ),
                            ("CADA", "Centres d’accueil de demandeurs d’asile (CADA)"),
                            ("CAF", "Caisses d’allocation familiale (CAF)"),
                            ("CAP_EMPLOI", "Cap Emploi"),
                            ("CAVA", "Centres d’adaptation à la vie active (CAVA)"),
                            ("CC", "Communautés de Commune"),
                            ("CCAS", "Centres communaux d’action sociale (CCAS)"),
                            ("CCONS", "Chambres consulaires (CCI, CMA, CA)"),
                            ("CD", "Conseils Départementaux (CD)"),
                            ("CDAS", "Centre Départementale d’Action Sociale (CDAS)"),
                            ("CFP", "Centre des Finances Publiques (CFP)"),
                            (
                                "CHRS",
                                "Centres d’hébergement et de réinsertion sociale (CHRS)",
                            ),
                            ("CHU", "Centres d’hébergement d’urgence (CHU)"),
                            ("CIAS", "Centres intercommunaux d’action sociale (CIAS)"),
                            (
                                "CIDFF",
                                "Centres d’information sur les droits des femmes et des familles (CIDFF)",
                            ),
                            ("CITMET", "Cité des métiers"),
                            ("CMP", "Centre Médico-Psychologique (CMP)"),
                            ("CMS", "Centre Médico-Social (CMS)"),
                            ("CPAM", "Caisse Primaire d’Assurance Maladie (CPAM)"),
                            ("CPH", "Centres provisoires d’hébergement (CPH)"),
                            ("CS", "Centre social"),
                            (
                                "CSAPA",
                                "CSAPA - Centre de soins, d’accompagnement et de prévention en addictologie",
                            ),
                            ("CSC", "Centre Socio-Culturel (CSC)"),
                            (
                                "DEETS",
                                "Directions de l’Economie, de l’Emploi, du Travail et des Solidarités (DEETS)",
                            ),
                            ("DEPT", "Services sociaux du Conseil départemental"),
                            (
                                "DIPLP",
                                "Délégation interministérielles à la prévention et à la lutte contre la pauvreté",
                            ),
                            ("E2C", "E2C - École de la 2e chance"),
                            ("EA", "Entreprise adaptée (EA)"),
                            ("EATT", "Entreprise Adaptée (EATT)"),
                            ("EI", "Entreprises d’insertion (EI)"),
                            (
                                "EITI",
                                "Entreprises d’insertion par le travail indépendant (EITI)",
                            ),
                            ("ENM", "Espace Numérique Mobile (ENM)"),
                            ("EPCI", "Intercommunalité (EPCI)"),
                            ("EPI", "Espace Public Internet (EPI)"),
                            (
                                "EPIDE",
                                "EPIDE - Établissement pour l’insertion dans l’emploi",
                            ),
                            ("EPN", "Espace Public Numérique (EPN)"),
                            ("ES", "Épicerie Solidaire"),
                            ("ESS", "Entreprise de l’Économie Sociale et Solidaire"),
                            ("ETABL_PRI", "Établissement privé"),
                            ("ETABL_PUB", "Établissement public"),
                            ("ETAT", "Service de l’État"),
                            (
                                "ETTI",
                                "Entreprises de travail temporaire d’insertion (ETTI)",
                            ),
                            ("EVS", "Espace de Vie Sociale (EVS)"),
                            ("FABLAB", "Fablab / Atelier partagé"),
                            (
                                "FAIS",
                                "Fédérations d’acteurs de l’insertion et de la solidarité",
                            ),
                            ("FT", "France Travail"),
                            (
                                "GEIQ",
                                "Groupements d’employeurs pour l’insertion et la qualification (GEIQ)",
                            ),
                            (
                                "HUDA",
                                "HUDA - Hébergement d’urgence pour demandeurs d’asile",
                            ),
                            ("LA_POSTE", "Bureau de poste / Agence postale"),
                            ("MDA", "Maison Départementale de l’Autonomie"),
                            ("MDE", "Maison de l’emploi"),
                            ("MDEF", "Maison de l’emploi et de la formation"),
                            ("MDPH", "Maison Départementale des Personnes Handicapées"),
                            ("MDS", "Maison Départementale des Solidarités"),
                            ("MJC", "Maison des jeunes et de la culture"),
                            ("ML", "Mission Locale"),
                            ("MQ", "Maison de quartier"),
                            ("MSA", "Mutualité Sociale Agricole"),
                            ("MSAP", "Maison de Services Au Public (MSAP)"),
                            ("MUNI", "Municipalités"),
                            (
                                "OACAS",
                                "Structures agréées Organisme d’accueil communautaire et d’activité solidaire (OACAS)",
                            ),
                            ("ODC", "Organisation délégataire d’un CD"),
                            ("OF", "Organisme de formations"),
                            ("OIL", "Opérateur d’intermédiation locative"),
                            ("OPCS", "Organisation porteuse de la clause sociale"),
                            ("PAD", "Point d’Accès au Droit"),
                            ("PENSION", "Pension de famille / résidence accueil"),
                            ("PI", "Point Information (PI)"),
                            (
                                "PIJ_BIJ",
                                "Points et bureaux information jeunesse (PIJ/BIJ)",
                            ),
                            (
                                "PIMMS",
                                "Point Information Médiation Multi Services (PIMMS)",
                            ),
                            ("PJJ", "Protection judiciaire de la jeunesse (PJJ)"),
                            (
                                "PLIE",
                                "Plans locaux pour l’insertion et l’emploi (PLIE)",
                            ),
                            ("PREF", "Préfecture, Sous-Préfecture"),
                            ("PREVENTION", "Service ou club de prévention"),
                            ("REG", "Région"),
                            ("RESSOURCERIE", "Ressourcerie"),
                            ("RFS", "Réseau France Services"),
                            (
                                "RS_FJT",
                                "Résidence sociale / FJT - Foyer de Jeunes Travailleurs",
                            ),
                            ("SCP", "Services et clubs de prévention"),
                            (
                                "SPIP",
                                "Services pénitentiaires d’insertion et de probation (SPIP)",
                            ),
                            ("TIERS_LIEUX", "Tiers lieu & coworking"),
                            ("UDAF", "Union Départementale d’Aide aux Familles (UDAF)"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("url", models.URLField(blank=True)),
                ("short_desc", models.CharField(blank=True, max_length=280)),
                ("full_desc", models.TextField(blank=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[dora.core.validators.validate_phone_number],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address1", models.CharField(blank=True, max_length=255)),
                ("address2", models.CharField(blank=True, max_length=255)),
                ("postal_code", models.CharField(blank=True, max_length=5)),
                ("city_code", models.CharField(blank=True, max_length=5)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("department", models.CharField(blank=True, max_length=3)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("geocoding_score", models.FloatField(blank=True, null=True)),
                ("ape", models.CharField(blank=True, max_length=6)),
                (
                    "accesslibre_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[dora.core.validators.validate_accesslibre_url],
                        verbose_name="URL accesslibre",
                    ),
                ),
                (
                    "opening_hours",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[dora.core.validators.validate_opening_hours_str],
                    ),
                ),
                (
                    "opening_hours_details",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "other_labels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(blank=True, null=True)),
                ("has_been_edited", models.BooleanField(default=False)),
                ("quick_start_done", models.BooleanField(default=False)),
                ("data_inclusion_id", models.TextField(blank=True, db_index=True)),
                ("data_inclusion_source", models.TextField(blank=True, db_index=True)),
                ("disable_orientation_form", models.BooleanField(default=False)),
                ("is_obsolete", models.BooleanField(db_index=True, default=False)),
                ("admin_already_invited", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="structures.structure",
                    ),
                ),
            ],
            bases=(itoutils.django.nexus.models.NexusModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StructureMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership",
                        to="structures.structure",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre",
            },
            bases=(itoutils.django.nexus.models.NexusModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="structure",
            name="members",
            field=models.ManyToManyField(
                through="structures.StructureMember", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="structure",
            name="national_labels",
            field=models.ManyToManyField(
                blank=True, to="structures.structurenationallabel"
            ),
        ),
        migrations.CreateModel(
            name="StructurePutativeMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("invited_by_admin", models.BooleanField(default=False)),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="putative_membership",
                        to="structures.structure",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="putative_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre Potentiel",
                "verbose_name_plural": "Membres Potentiels",
            },
        ),
        migrations.AddField(
            model_name="structure",
            name="putative_members",
            field=models.ManyToManyField(
                related_name="putative_structure_set",
                through="structures.StructurePutativeMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="structure",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="structures.structuresource",
            ),
        ),
        migrations.AddConstraint(
            model_name="structuremember",
            constraint=models.UniqueConstraint(
                fields=("user", "structure"), name="structures_unique_user_by_structure"
            ),
        ),
        migrations.AddConstraint(
            model_name="structureputativemember",
            constraint=models.UniqueConstraint(
                fields=("user", "structure"),
                name="structures_unique_putative_member_by_structure",
            ),
        ),
        migrations.AddConstraint(
            model_name="structure",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("siret__length", 14), ("siret__isnull", True), _connector="OR"
                ),
                name="structures_structure_valid_or_null_siren",
            ),
        ),
        migrations.AddConstraint(
            model_name="structure",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("siret__isnull", False), ("parent__isnull", False), _connector="OR"
                ),
                name="structures_structure_null_siret_only_in_branches",
            ),
        ),
    ]
