# Generated by Django 6.0.2 on 2026-03-04 16:00

from django.db import migrations

STRUCTURE_NATIONAL_LABELS = [
    ("80000-rebonds", "80 000 rebonds"),
    ("action-logement", "Action Logement"),
    ("arald", "Adhérent du Réseau Aloïs"),
    ("asile", "Asile"),
    ("afpa", "AFPA"),
    ("afeji", "AFEJI"),
    ("asep-rh", "ASEP-RH"),
    ("atlantis-connect", "Atlantis Connect"),
    ("alliance-villes-emploi", "Alliance villes emploi"),
    ("ana-ct", "ANA-CT"),
    ("apdc", "APDC"),
    ("apels", "APELS Agence Pour l'Éducation par Le Sport"),
    ("apprenons-chaque", "Apprenons chaque"),
    ("aptic", "APTIC"),
    ("banques-alimentaires", "Banques alimentaires"),
    ("bnf", "BNF"),
    ("caj", "CAJ"),
    ("cmg", "CMG"),
    ("caisse-connect", "Caisses connect"),
    ("cnf-bricol", "CNF Bricol - Niveau C-accès à"),
    ("cci", "CCI"),
    ("cma", "Chambre de Métiers et de l'Artisanat"),
    ("chantier-ecole", "Chantier école"),
    ("cnam", "CNAM"),
    ("cnaf", "CNAF"),
    ("college-departemental", "Collège Départemental"),
    ("conseil-departemental", "Conseil Départemental"),
    ("conseiller-numerique", "Conseiller numérique"),
    ("coorace", "Coorace"),
    ("cpram", "CPRAM"),
    ("crape", "CRAPE"),
    ("crir-lr", "CRIR-LR"),
    ("cresus", "CRÉSUS"),
    ("croix-rouge", "Croix Rouge"),
    ("dihai", "DIHAI"),
    ("due-for-a-job", "Due For A Job"),
    ("e2c-ecole-de-la-2e-chance", "E2C - École de la 2e chance"),
    ("eaje", "EAJE"),
    ("emeris", "Éméris"),
    ("envie", "Envie"),
    ("epa-d", "EPA-D"),
    ("espace-emploi-agri-agro", "Espace Emploi Agri-Agro"),
    ("efcld", "EFCLD"),
    ("fabrique-de-territoire", "Fabrique de Territoire"),
    (
        "federation-des-acteurs-de-la-solidarite",
        "Fédération des acteurs de la solidarité",
    ),
    (
        "federation-des-entreprises-d-insertion",
        "Fédération des entreprises d'insertion",
    ),
    ("federation-pro-femmes", "Fédération professionnelle Pour les femmes"),
    ("fnesa", "FNSEA"),
    ("force-femmes", "Force Femmes"),
    ("france-active", "France Active"),
    ("france-service", "France Service"),
    ("france-travail", "France Travail"),
    ("french-tech", "French Tech"),
    ("geiq", "GEIQ"),
    ("grandes-ecoles-du-numerique", "Grandes écoles du numérique"),
    ("grand-test-covoiturage-d-entreprise", "Grand Test Covoiturage d'entreprise"),
    ("hlap", "HLAP"),
    ("fnag", "FNAG"),
    ("initiative-france", "Initiative France"),
    ("jannadis", "Jannadis"),
    ("la-cravate-solidaire", "La Cravate Solidaire"),
    ("la-ressourcerie", "La Ressourcerie"),
    ("les-premieres", "Les Premières"),
    ("linkeusion", "Linkéusion"),
    ("maisons-de-l-emploi", "Maisons de l'Emploi"),
    ("medh", "MEDH"),
    ("mission-locale", "Mission Locale"),
    ("mut", "MUT"),
    ("naut-conseil-budget", "NAUT Conseil Budget"),
    ("point-justice", "Point Justice"),
    ("positive-planet", "Positive Planet"),
    ("recchi", "Recchi"),
    ("reseau-afp", "Réseau AFP"),
    ("reseau-entrepreneurs", "Réseau Entrepreneurs"),
    ("ressources", "Ressources"),
    ("revues-du-coeur", "Revues du Cœur"),
    ("s-c-conseil", "SC Conseil"),
    ("secours-populaire", "Secours Populaire"),
    ("smo", "SMO"),
    ("simplan", "Simplan"),
    ("smesa", "SMESA"),
    ("slime", "SLIME"),
    ("smo-solidarite-nouvelle-face", "SMO - Solidarité Nouvelle Face au Chômage"),
    ("sport-dans-la-ville", "Sport Dans La Ville"),
    (
        "structures-d-insertion-par-l-activite-economique",
        "Structures d'insertion par l'activité économique",
    ),
    ("tous-tes-possibles", "Tous Tes Possibles"),
    ("120ld", "120LD"),
    ("uniae", "UNIAE"),
    ("univa", "UNIVA"),
    ("urban-valonnais-du-pays-aux", "Urban Valonnais du Pays aux"),
    (
        "urban-valorise-des-territoires-communs",
        "Urban Valorise des territoires communs",
    ),
    ("utp-cifa", "UTP-CIFA"),
    ("yumeooh", "Yumeooh"),
]


def load_structure_national_labels(apps, schema_editor):
    StructureNationalLabel = apps.get_model("structures", "StructureNationalLabel")
    for value, label in STRUCTURE_NATIONAL_LABELS:
        StructureNationalLabel.objects.get_or_create(
            value=value,
            label=label,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            load_structure_national_labels,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
