# Generated by Django 6.0.5 on 2026-07-29 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0002_seed_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="branches",
                to="structures.structure",
            ),
        ),
        migrations.AlterField(
            model_name="structuremember",
            name="structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="membership",
                to="structures.structure",
            ),
        ),
        migrations.AlterField(
            model_name="structureputativemember",
            name="structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="putative_membership",
                to="structures.structure",
            ),
        ),
    ]
