# Generated by Django 6.1.1 on 2026-09-24 14:57

from django.db import migrations, models


def replace_in_progress(apps, schema_editor):
    Structure = apps.get_model("structures", "Structure")
    Structure.objects.filter(moderation_status="IN_PROGRESS").update(
        moderation_status="NEED_NEW_MODERATION"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0004_structure_reseaux_porteurs"),
    ]

    operations = [
        migrations.RunPython(replace_in_progress, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="structure",
            name="moderation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEED_INITIAL_MODERATION", "Première modération nécessaire"),
                    ("NEED_NEW_MODERATION", "Nouvelle modération nécessaire"),
                    ("VALIDATED", "Validé"),
                ],
                db_index=True,
                max_length=30,
                null=True,
                verbose_name="Modération",
            ),
        ),
    ]
