# Generated by Django 4.2.19 on 2025-02-24 17:21

from django.db import migrations, models

import dora.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0073_add_label_conseil_departemental"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="code_safir_pe",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=5,
                null=True,
                unique=True,
                validators=[dora.core.validators.validate_safir],
                verbose_name="code SAFIR France Travail",
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="siret",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                unique=True,
                validators=[dora.core.validators.validate_siret],
                verbose_name="SIRET",
            ),
        ),
    ]
