# Generated by Django 5.2.6 on 2025-10-03 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0075_nodoraformdistructure"),
    ]

    operations = [
        migrations.RenameField(
            model_name="structure",
            old_name="code_safir_pe",
            new_name="code_safir_ft",
        ),
    ]
