# Generated by Django 4.2.5 on 2026-02-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0077_rename_structure_sources_to_ft"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="admin_already_invited",
            field=models.BooleanField(default=False),
        ),
    ]
