# Generated by Django 6.0.2 on 2026-03-02 14:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("orphan_structures", "Orphan Structures"),
                            ("service_activation", "Service Activation"),
                            ("invited_users", "Invited Users"),
                            ("self_invited_users", "Self Invited Users"),
                            ("users_without_structure", "Users Without Structure"),
                            ("user_account_deletion", "User Account Deletion"),
                            (
                                "manager_structure_moderation",
                                "Manager Structure Moderation",
                            ),
                            ("service_editors", "Service Editors"),
                            ("generic_task", "Generic Task"),
                        ],
                        verbose_name="type de tâche",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("complete", "Complete"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        verbose_name="Statut",
                    ),
                ),
                (
                    "counter",
                    models.IntegerField(default=0, verbose_name="compteur d'exécution"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date d'expiration"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("orphan_structures", "Orphan Structures"),
                            ("service_activation", "Service Activation"),
                            ("invited_users", "Invited Users"),
                            ("self_invited_users", "Self Invited Users"),
                            ("users_without_structure", "Users Without Structure"),
                            ("user_account_deletion", "User Account Deletion"),
                            (
                                "manager_structure_moderation",
                                "Manager Structure Moderation",
                            ),
                            ("service_editors", "Service Editors"),
                            ("generic_task", "Generic Task"),
                        ],
                        verbose_name="type de tâche",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("complete", "Complete"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        verbose_name="Statut",
                    ),
                ),
                (
                    "counter",
                    models.IntegerField(default=0, verbose_name="compteur d'exécution"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de déclenchement"
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="propriétaire"
                    ),
                ),
            ],
            options={
                "verbose_name": "historique de notification",
            },
        ),
    ]
