# Generated by Django 6.0.2 on 2026-03-02 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("notifications", "0001_initial"),
        ("structures", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="owner_structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="structures.structure",
                verbose_name="structure propriétaire",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="owner_structureputativemember",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="structures.structureputativemember",
                verbose_name="invitation propriétaire",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="owner_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur propriétaire",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="notification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="notifications.notification",
                verbose_name="notification parente",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["updated_at"], name="notificatio_updated_8e4673_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["task_type"], name="notificatio_task_ty_854c21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["status"], name="notificatio_status_d92267_idx"),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("owner_structure", None), _negated=True),
                    models.Q(("owner_user", None), _negated=True),
                    models.Q(("owner_structureputativemember", None), _negated=True),
                    _connector="OR",
                ),
                name="check_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("task_type", "owner_structure"),
                name="unique_task_for_structure",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("task_type", "owner_user"), name="unique_task_for_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("task_type", "owner_structureputativemember"),
                name="unique_task_for_invitation",
            ),
        ),
    ]
