# Generated by Django 4.2.17 on 2025-01-13 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0114_service_duration_weekly_hours_service_duration_weeks"),
        ("notifications", "0007_alter_notification_task_type_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="check_owner",
        ),
        migrations.AddField(
            model_name="notification",
            name="owner_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="services.service",
                verbose_name="service propriétaire",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("owner_structure", None), _negated=True),
                    models.Q(("owner_user", None), _negated=True),
                    models.Q(("owner_structureputativemember", None), _negated=True),
                    models.Q(("owner_service", None), _negated=True),
                    _connector="OR",
                ),
                name="check_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("task_type", "owner_service"), name="unique_task_for_service"
            ),
        ),
    ]
