# Generated by Django 6.0.2 on 2026-03-02 14:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orientations", "0002_initial"),
        ("services", "0002_initial"),
        ("structures", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeploymentState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_code", models.CharField(blank=True, max_length=3)),
                ("department_name", models.CharField(max_length=230)),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (0, "Aucun contact"),
                            (1, "En cours d'échanges"),
                            (2, "Premières saisies de services"),
                            (3, "Déploiement en cours"),
                            (4, "Finalisation du déploiement"),
                        ],
                        default=0,
                        verbose_name="État de déploiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "État de déploiement",
                "verbose_name_plural": "État de déploiement",
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("anonymous_user_hash", models.CharField(blank=True, max_length=32)),
                ("is_logged", models.BooleanField()),
                ("is_staff", models.BooleanField()),
                ("is_manager", models.BooleanField()),
                ("is_an_admin", models.BooleanField()),
                (
                    "user_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accompagnateur", "Accompagnateur"),
                            ("offreur", "Offreur"),
                            ("accompagnateur_offreur", "Accompagnateur et offreur"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Activité principale de l'utilisateur",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SearchView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("anonymous_user_hash", models.CharField(blank=True, max_length=32)),
                ("is_logged", models.BooleanField()),
                ("is_staff", models.BooleanField()),
                ("is_manager", models.BooleanField()),
                ("is_an_admin", models.BooleanField()),
                (
                    "user_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accompagnateur", "Accompagnateur"),
                            ("offreur", "Offreur"),
                            ("accompagnateur_offreur", "Accompagnateur et offreur"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Activité principale de l'utilisateur",
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, db_index=True, max_length=3),
                ),
                (
                    "city_code",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        verbose_name="Code INSEE de la recherche",
                    ),
                ),
                ("num_results", models.IntegerField()),
                ("num_di_results", models.IntegerField(default=0)),
                ("num_di_results_top10", models.IntegerField(default=0)),
                (
                    "results_slugs_top10",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True), default=list
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="services.servicecategory"
                    ),
                ),
                (
                    "fee_conditions",
                    models.ManyToManyField(
                        blank=True,
                        to="services.servicefee",
                        verbose_name="Frais à charge",
                    ),
                ),
                (
                    "kinds",
                    models.ManyToManyField(
                        blank=True,
                        to="services.servicekind",
                        verbose_name="Type de service",
                    ),
                ),
                (
                    "location_kinds",
                    models.ManyToManyField(
                        blank=True,
                        to="services.locationkind",
                        verbose_name="Lieu de déroulement",
                    ),
                ),
                (
                    "subcategories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="services.servicesubcategory"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrientationView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("anonymous_user_hash", models.CharField(blank=True, max_length=32)),
                ("is_logged", models.BooleanField()),
                ("is_staff", models.BooleanField()),
                ("is_manager", models.BooleanField()),
                ("is_an_admin", models.BooleanField()),
                (
                    "user_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accompagnateur", "Accompagnateur"),
                            ("offreur", "Offreur"),
                            ("accompagnateur_offreur", "Accompagnateur et offreur"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Activité principale de l'utilisateur",
                    ),
                ),
                ("is_structure_member", models.BooleanField()),
                ("is_structure_admin", models.BooleanField()),
                (
                    "structure_department",
                    models.CharField(blank=True, db_index=True, max_length=3),
                ),
                (
                    "structure_city_code",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        verbose_name="Code INSEE de la structure",
                    ),
                ),
                (
                    "structure_source",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "update_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEEDED", "Actualisation conseillée"),
                            ("NOT_NEEDED", "Service à jour"),
                            ("REQUIRED", "Actualisation exigée"),
                        ],
                        max_length=10,
                        verbose_name="Statut d'actualisation",
                    ),
                ),
                (
                    "update_needed",
                    models.BooleanField(
                        default=False, verbose_name="Mise à jour nécessaire"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUGGESTION", "Suggestion"),
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "service_source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="La source de l'import de ce service",
                        max_length=255,
                    ),
                ),
                (
                    "orientation_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MODÉRATION_EN_COURS", "En cours de modération"),
                            ("MODÉRATION_REJETÉE", "Rejetée par la modération"),
                            ("OUVERTE", "Ouverte / En cours de traitement"),
                            ("VALIDÉE", "Validée"),
                            ("REFUSÉE", "Refusée"),
                            ("EXPIRÉE", "Expirée"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("is_di", models.BooleanField(db_index=True, default=False)),
                ("di_structure_name", models.CharField(default="", max_length=255)),
                ("di_service_id", models.CharField(default="", max_length=255)),
                ("di_service_name", models.CharField(default="", max_length=255)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="services.servicecategory"
                    ),
                ),
                (
                    "orientation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orientations.orientation",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.service",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structures.structure",
                    ),
                ),
                (
                    "subcategories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="services.servicesubcategory"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "search_view",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stats.searchview",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MobilisationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("anonymous_user_hash", models.CharField(blank=True, max_length=32)),
                ("is_logged", models.BooleanField()),
                ("is_staff", models.BooleanField()),
                ("is_manager", models.BooleanField()),
                ("is_an_admin", models.BooleanField()),
                (
                    "user_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accompagnateur", "Accompagnateur"),
                            ("offreur", "Offreur"),
                            ("accompagnateur_offreur", "Accompagnateur et offreur"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Activité principale de l'utilisateur",
                    ),
                ),
                ("is_structure_member", models.BooleanField()),
                ("is_structure_admin", models.BooleanField()),
                (
                    "structure_department",
                    models.CharField(blank=True, db_index=True, max_length=3),
                ),
                (
                    "structure_city_code",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        verbose_name="Code INSEE de la structure",
                    ),
                ),
                (
                    "structure_source",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "update_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEEDED", "Actualisation conseillée"),
                            ("NOT_NEEDED", "Service à jour"),
                            ("REQUIRED", "Actualisation exigée"),
                        ],
                        max_length=10,
                        verbose_name="Statut d'actualisation",
                    ),
                ),
                (
                    "update_needed",
                    models.BooleanField(
                        default=False, verbose_name="Mise à jour nécessaire"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUGGESTION", "Suggestion"),
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "service_source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="La source de l'import de ce service",
                        max_length=255,
                    ),
                ),
                (
                    "external_link",
                    models.URLField(blank=True, null=True, verbose_name="lien externe"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="services.servicecategory"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.service",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structures.structure",
                    ),
                ),
                (
                    "subcategories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="services.servicesubcategory"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "search_view",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stats.searchview",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DiServiceView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("anonymous_user_hash", models.CharField(blank=True, max_length=32)),
                ("is_logged", models.BooleanField()),
                ("is_staff", models.BooleanField()),
                ("is_manager", models.BooleanField()),
                ("is_an_admin", models.BooleanField()),
                (
                    "user_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accompagnateur", "Accompagnateur"),
                            ("offreur", "Offreur"),
                            ("accompagnateur_offreur", "Accompagnateur et offreur"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Activité principale de l'utilisateur",
                    ),
                ),
                ("structure_id", models.CharField(default="", max_length=255)),
                ("structure_name", models.CharField(default="", max_length=255)),
                (
                    "structure_department",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=3
                    ),
                ),
                ("service_id", models.CharField(default="", max_length=255)),
                ("service_name", models.CharField(default="", max_length=255)),
                ("source", models.CharField(default="", max_length=255)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="services.servicecategory"
                    ),
                ),
                (
                    "subcategories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="services.servicesubcategory"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "search_view",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stats.searchview",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DiMobilisationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("anonymous_user_hash", models.CharField(blank=True, max_length=32)),
                ("is_logged", models.BooleanField()),
                ("is_staff", models.BooleanField()),
                ("is_manager", models.BooleanField()),
                ("is_an_admin", models.BooleanField()),
                (
                    "user_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accompagnateur", "Accompagnateur"),
                            ("offreur", "Offreur"),
                            ("accompagnateur_offreur", "Accompagnateur et offreur"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Activité principale de l'utilisateur",
                    ),
                ),
                ("structure_id", models.CharField(default="", max_length=255)),
                ("structure_name", models.CharField(default="", max_length=255)),
                (
                    "structure_department",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=3
                    ),
                ),
                ("service_id", models.CharField(default="", max_length=255)),
                ("service_name", models.CharField(default="", max_length=255)),
                ("source", models.CharField(default="", max_length=255)),
                (
                    "external_link",
                    models.URLField(blank=True, null=True, verbose_name="lien externe"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="services.servicecategory"
                    ),
                ),
                (
                    "subcategories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="services.servicesubcategory"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "search_view",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stats.searchview",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("anonymous_user_hash", models.CharField(blank=True, max_length=32)),
                ("is_logged", models.BooleanField()),
                ("is_staff", models.BooleanField()),
                ("is_manager", models.BooleanField()),
                ("is_an_admin", models.BooleanField()),
                (
                    "user_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accompagnateur", "Accompagnateur"),
                            ("offreur", "Offreur"),
                            ("accompagnateur_offreur", "Accompagnateur et offreur"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Activité principale de l'utilisateur",
                    ),
                ),
                ("is_structure_member", models.BooleanField()),
                ("is_structure_admin", models.BooleanField()),
                (
                    "structure_department",
                    models.CharField(blank=True, db_index=True, max_length=3),
                ),
                (
                    "structure_city_code",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        verbose_name="Code INSEE de la structure",
                    ),
                ),
                (
                    "update_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEEDED", "Actualisation conseillée"),
                            ("NOT_NEEDED", "Service à jour"),
                            ("REQUIRED", "Actualisation exigée"),
                        ],
                        max_length=10,
                        verbose_name="Statut d'actualisation",
                    ),
                ),
                (
                    "update_needed",
                    models.BooleanField(
                        default=False, verbose_name="Mise à jour nécessaire"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUGGESTION", "Suggestion"),
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "service_source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="La source de l'import de ce service",
                        max_length=255,
                    ),
                ),
                ("is_di", models.BooleanField(db_index=True, default=False)),
                (
                    "recipient_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "recipient_kind",
                    models.CharField(
                        choices=[
                            ("beneficiary", "Bénéficiaire"),
                            ("professional", "Professionnel"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "structure_source",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("di_structure_name", models.CharField(default="", max_length=255)),
                ("di_service_id", models.CharField(default="", max_length=255)),
                ("di_service_name", models.CharField(default="", max_length=255)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="services.servicecategory"
                    ),
                ),
                (
                    "search_view",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stats.searchview",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.service",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structures.structure",
                    ),
                ),
                (
                    "subcategories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="services.servicesubcategory"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("anonymous_user_hash", models.CharField(blank=True, max_length=32)),
                ("is_logged", models.BooleanField()),
                ("is_staff", models.BooleanField()),
                ("is_manager", models.BooleanField()),
                ("is_an_admin", models.BooleanField()),
                (
                    "user_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accompagnateur", "Accompagnateur"),
                            ("offreur", "Offreur"),
                            ("accompagnateur_offreur", "Accompagnateur et offreur"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Activité principale de l'utilisateur",
                    ),
                ),
                ("is_structure_member", models.BooleanField()),
                ("is_structure_admin", models.BooleanField()),
                (
                    "structure_department",
                    models.CharField(blank=True, db_index=True, max_length=3),
                ),
                (
                    "structure_city_code",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        verbose_name="Code INSEE de la structure",
                    ),
                ),
                (
                    "structure_source",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "update_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEEDED", "Actualisation conseillée"),
                            ("NOT_NEEDED", "Service à jour"),
                            ("REQUIRED", "Actualisation exigée"),
                        ],
                        max_length=10,
                        verbose_name="Statut d'actualisation",
                    ),
                ),
                (
                    "update_needed",
                    models.BooleanField(
                        default=False, verbose_name="Mise à jour nécessaire"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUGGESTION", "Suggestion"),
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "service_source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="La source de l'import de ce service",
                        max_length=255,
                    ),
                ),
                ("is_orientable", models.BooleanField(blank=True, default=False)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="services.servicecategory"
                    ),
                ),
                (
                    "search_view",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stats.searchview",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.service",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structures.structure",
                    ),
                ),
                (
                    "subcategories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="services.servicesubcategory"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StructureInfosView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("anonymous_user_hash", models.CharField(blank=True, max_length=32)),
                ("is_logged", models.BooleanField()),
                ("is_staff", models.BooleanField()),
                ("is_manager", models.BooleanField()),
                ("is_an_admin", models.BooleanField()),
                (
                    "user_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accompagnateur", "Accompagnateur"),
                            ("offreur", "Offreur"),
                            ("accompagnateur_offreur", "Accompagnateur et offreur"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Activité principale de l'utilisateur",
                    ),
                ),
                ("is_structure_member", models.BooleanField()),
                ("is_structure_admin", models.BooleanField()),
                (
                    "structure_department",
                    models.CharField(blank=True, db_index=True, max_length=3),
                ),
                (
                    "structure_city_code",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        verbose_name="Code INSEE de la structure",
                    ),
                ),
                (
                    "structure_source",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structures.structure",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "clic sur contacts de la structure",
                "verbose_name_plural": "clics sur contacts de la structure",
            },
        ),
        migrations.CreateModel(
            name="StructureView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("anonymous_user_hash", models.CharField(blank=True, max_length=32)),
                ("is_logged", models.BooleanField()),
                ("is_staff", models.BooleanField()),
                ("is_manager", models.BooleanField()),
                ("is_an_admin", models.BooleanField()),
                (
                    "user_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accompagnateur", "Accompagnateur"),
                            ("offreur", "Offreur"),
                            ("accompagnateur_offreur", "Accompagnateur et offreur"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Activité principale de l'utilisateur",
                    ),
                ),
                ("is_structure_member", models.BooleanField()),
                ("is_structure_admin", models.BooleanField()),
                (
                    "structure_department",
                    models.CharField(blank=True, db_index=True, max_length=3),
                ),
                (
                    "structure_city_code",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        verbose_name="Code INSEE de la structure",
                    ),
                ),
                (
                    "structure_source",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structures.structure",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
