# Generated by Django 6.0.6 on 2026-07-08 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0002_searchview_keyword_searchview_search_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="structureview",
            name="search_view",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stats.searchview",
            ),
        ),
    ]
