# Generated by Django 6.0.7 on 2026-07-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0003_structureview_search_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchview",
            name="region",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=2,
                verbose_name="Code de la région de la recherche",
            ),
        ),
    ]
