# Generated by Django 6.0.8 on 2026-09-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0005_searchview_kinds_array"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orientationview",
            name="orientation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MODÉRATION_EN_COURS", "En cours de modération"),
                    ("MODÉRATION_REJETÉE", "Rejetée par la modération"),
                    ("OUVERTE", "En cours de traitement"),
                    ("VALIDÉE", "Validée"),
                    ("REFUSÉE", "Déclinée"),
                    ("EXPIRÉE", "Expirée"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
