# Generated by Django 6.1.1 on 2026-09-28 08:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0006_alter_orientationview_orientation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchview",
            name="kinds",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("accompagnement", "Accompagnement"),
                        ("aide-financiere", "Aide financière"),
                        ("aide-materielle", "Aide matérielle"),
                        ("atelier", "Atelier"),
                        ("formation", "Formation"),
                        ("information", "Information"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                verbose_name="Types de service",
            ),
        ),
    ]
