# Generated by Django 4.2.16 on 2024-12-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0020_dimobilisationevent_external_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orientationview",
            name="orientation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MODÉRATION_EN_COURS", "En cours de modération"),
                    ("MODÉRATION_REJETÉE", "Rejetée par la modération"),
                    ("OUVERTE", "Ouverte / En cours de traitement"),
                    ("VALIDÉE", "Validée"),
                    ("REFUSÉE", "Refusée"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
