# Generated by Django 4.2.18 on 2025-02-14 16:24

from django.db import migrations, models


def set_update_needed(apps, schema_editor):
    MobilisationEvent = apps.get_model("stats", "MobilisationEvent")
    OrientationView = apps.get_model("stats", "OrientationView")
    ServiceShare = apps.get_model("stats", "ServiceShare")
    ServiceView = apps.get_model("stats", "ServiceView")

    # Update each model based on update_status
    for Model in [MobilisationEvent, OrientationView, ServiceShare, ServiceView]:
        Model.objects.filter(update_status__in=["NEEDED", "REQUIRED"]).update(
            update_needed=True
        )


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0021_alter_orientationview_orientation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobilisationevent",
            name="update_needed",
            field=models.BooleanField(
                default=False, verbose_name="Mise à jour nécessaire"
            ),
        ),
        migrations.AddField(
            model_name="orientationview",
            name="update_needed",
            field=models.BooleanField(
                default=False, verbose_name="Mise à jour nécessaire"
            ),
        ),
        migrations.AddField(
            model_name="serviceshare",
            name="update_needed",
            field=models.BooleanField(
                default=False, verbose_name="Mise à jour nécessaire"
            ),
        ),
        migrations.AddField(
            model_name="serviceview",
            name="update_needed",
            field=models.BooleanField(
                default=False, verbose_name="Mise à jour nécessaire"
            ),
        ),
        migrations.RunPython(set_update_needed, reverse_code=migrations.RunPython.noop),
    ]
