# Generated by Django 5.2.8 on 2025-12-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0022_mobilisationevent_update_needed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orientationview",
            name="orientation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MODÉRATION_EN_COURS", "En cours de modération"),
                    ("MODÉRATION_REJETÉE", "Rejetée par la modération"),
                    ("OUVERTE", "Ouverte / En cours de traitement"),
                    ("VALIDÉE", "Validée"),
                    ("REFUSÉE", "Refusée"),
                    ("EXPIRÉE", "Expirée"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
