repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        name: Ruff (Flake8)
        args: [--fix]
      - id: ruff-format
        name: Ruff format (Black + isort)
        args: [--check]

  - repo: https://github.com/thoughtworks/talisman
    rev: v1.32.0
    hooks:
      - id: talisman-commit
        name: Talisman
        entry: cmd --githook pre-commit

  - repo: https://github.com/rtts/djhtml
    rev: 3.0.7
    hooks:
      - id: djhtml
        types: [file]
        files: \.(html|mjml)$
        args: ["--tabwidth=2"]
