# Generated by Django 6.0.2 on 2026-03-02 14:46

import datetime
import uuid

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models

import dora.services.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
            ],
            options={
                "verbose_name": "Critère d’admission",
                "verbose_name_plural": "Critères d’admission",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BeneficiaryAccessMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Mode d'orientation bénéficiaire",
                "verbose_name_plural": "Modes d'orientation bénéficiaire",
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("di_id", models.TextField(blank=True)),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoachOrientationMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Mode d'orientation accompagnateur",
                "verbose_name_plural": "Modes d'orientation accompagnateur",
            },
        ),
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
            ],
            options={
                "verbose_name": "Justificatif à fournir",
                "verbose_name_plural": "Justificatifs à fournir",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FranceTravailOrientableService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "service France Travail orientable",
                "verbose_name_plural": "services France Travail orientables",
            },
        ),
        migrations.CreateModel(
            name="FundingLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Label de financement",
                "verbose_name_plural": "Labels de financement",
            },
        ),
        migrations.CreateModel(
            name="LocationKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Lieu de déroulement",
                "verbose_name_plural": "Lieux de déroulement",
            },
        ),
        migrations.CreateModel(
            name="Public",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                (
                    "corresponding_di_publics",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            max_length=255,
                            validators=[
                                dora.services.models.validate_corresponding_di_publics
                            ],
                        ),
                        default=list,
                        verbose_name="Publics Data Inclusion correspondants",
                    ),
                ),
            ],
            options={
                "verbose_name": "Public",
                "verbose_name_plural": "Publics",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
            ],
            options={
                "verbose_name": "Pré-requis ou compétence",
                "verbose_name_plural": "Pré-requis ou compétences",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "city_code",
                    models.CharField(verbose_name="Code INSEE de la recherche"),
                ),
                ("city_label", models.CharField(verbose_name="Label de la ville")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("NEVER", "Jamais"),
                            ("TWO_WEEKS", "Tous les 15 jours"),
                            ("MONTHLY", "Mensuel"),
                        ],
                        default="TWO_WEEKS",
                        max_length=10,
                        verbose_name="Fréquence",
                    ),
                ),
                (
                    "last_notification_date",
                    models.DateField(default=datetime.datetime.now),
                ),
            ],
            options={
                "verbose_name": "Recherche sauvegardé",
                "verbose_name_plural": "Recherches sauvegardées",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "moderation_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "NEED_INITIAL_MODERATION",
                                "Première modération nécessaire",
                            ),
                            ("NEED_NEW_MODERATION", "Nouvelle modération nécessaire"),
                            ("IN_PROGRESS", "En cours"),
                            ("VALIDATED", "Validé"),
                        ],
                        db_index=True,
                        max_length=30,
                        null=True,
                        verbose_name="Modération",
                    ),
                ),
                ("moderation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=140, verbose_name="Nom de l’offre"),
                ),
                (
                    "short_desc",
                    models.TextField(blank=True, max_length=280, verbose_name="Résumé"),
                ),
                (
                    "full_desc",
                    models.TextField(
                        blank=True, verbose_name="Descriptif complet de l’offre"
                    ),
                ),
                (
                    "is_cumulative",
                    models.BooleanField(
                        default=True, verbose_name="Solution cumulable"
                    ),
                ),
                (
                    "fee_details",
                    models.TextField(blank=True, verbose_name="Détail des frais"),
                ),
                (
                    "beneficiaries_access_modes_external_form_link",
                    models.URLField(
                        blank=True, verbose_name="Lien vers le formulaire externe"
                    ),
                ),
                (
                    "beneficiaries_access_modes_external_form_link_text",
                    models.CharField(
                        blank=True,
                        max_length=27,
                        verbose_name="L’intitulé du lien vers le formulaire externe",
                    ),
                ),
                (
                    "beneficiaries_access_modes_other",
                    models.CharField(blank=True, max_length=280, verbose_name="Autre"),
                ),
                (
                    "coach_orientation_modes_external_form_link",
                    models.URLField(
                        blank=True, verbose_name="Lien vers le formulaire externe"
                    ),
                ),
                (
                    "coach_orientation_modes_external_form_link_text",
                    models.CharField(
                        blank=True,
                        max_length=27,
                        verbose_name="L’intitulé du lien vers le formulaire externe",
                    ),
                ),
                (
                    "coach_orientation_modes_other",
                    models.CharField(blank=True, max_length=280, verbose_name="Autre"),
                ),
                (
                    "forms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1024),
                        blank=True,
                        default=list,
                        verbose_name="Partagez les documents à compléter",
                    ),
                ),
                (
                    "online_form",
                    models.URLField(
                        blank=True, verbose_name="Formulaire en ligne à compléter"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True,
                        max_length=140,
                        verbose_name="Nom du contact référent",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Numéro de téléphone"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Courriel"
                    ),
                ),
                (
                    "is_contact_info_public",
                    models.BooleanField(
                        default=False, verbose_name="Rendre mes informations publiques"
                    ),
                ),
                (
                    "remote_url",
                    models.URLField(blank=True, verbose_name="Lien visioconférence"),
                ),
                (
                    "address1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse"
                    ),
                ),
                (
                    "address2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Compléments d’adresse"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Code postal"
                    ),
                ),
                (
                    "city_code",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Code INSEE"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=255, verbose_name="Ville"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "diffusion_zone_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("city", "Commune"),
                            ("epci", "Intercommunalité (EPCI)"),
                            ("department", "Département"),
                            ("region", "Région"),
                            ("country", "France entière"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="Zone de diffusion",
                    ),
                ),
                (
                    "diffusion_zone_details",
                    models.CharField(blank=True, db_index=True, max_length=9),
                ),
                ("qpv_or_zrr", models.BooleanField(default=False)),
                (
                    "recurrence",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="Récurrence"
                    ),
                ),
                (
                    "suspension_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="Jusqu’au"
                    ),
                ),
                (
                    "appointment_link",
                    models.URLField(
                        blank=True, verbose_name="Lien de prise de rendez-vous"
                    ),
                ),
                (
                    "duration_weekly_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre d'heures par semaine pour effectuer ce service. (par défaut, 1)",
                        null=True,
                        verbose_name="Nombre d'heures par semaine",
                    ),
                ),
                (
                    "duration_weeks",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre de semaines que durent le service (par défaut, 1)",
                        null=True,
                        verbose_name="Nombre de semaines",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUGGESTION", "Suggestion"),
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        max_length=20,
                        null=True,
                        verbose_name="Statut",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(blank=True, null=True)),
                ("publication_date", models.DateTimeField(blank=True, null=True)),
                ("is_model", models.BooleanField(default=False)),
                ("sync_checksum", models.CharField(blank=True, max_length=32)),
                ("last_sync_checksum", models.CharField(blank=True, max_length=32)),
                ("use_inclusion_numerique_scheme", models.BooleanField(default=False)),
                ("data_inclusion_id", models.TextField(blank=True, db_index=True)),
                ("data_inclusion_source", models.TextField(blank=True, db_index=True)),
                (
                    "update_frequency",
                    models.CharField(
                        choices=[
                            (
                                "tous-les-mois",
                                "Très souvent, je veux recevoir une alerte tous les mois",
                            ),
                            (
                                "tous-les-3-mois",
                                "Régulièrement, je veux recevoir une alerte tous les 3 mois",
                            ),
                            (
                                "tous-les-6-mois",
                                "Occasionnellement, je veux recevoir une alerte tous les 6 mois",
                            ),
                            (
                                "tous-les-12-mois",
                                "Très rarement, je veux recevoir une alerte tous les 12 mois",
                            ),
                            (
                                "tous-les-16-mois",
                                "Presque jamais, je veux recevoir une alerte tous les 16 mois",
                            ),
                            ("jamais", "Jamais, les informations n’évoluent jamais"),
                        ],
                        db_index=True,
                        default="tous-les-6-mois",
                        max_length=16,
                        verbose_name="Fréquence de mise à jour",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("is_obsolete", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Catégorie principale",
                "verbose_name_plural": "Catégories principales",
            },
        ),
        migrations.CreateModel(
            name="ServiceFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Frais à charge",
            },
        ),
        migrations.CreateModel(
            name="ServiceKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Type de service",
                "verbose_name_plural": "Types de service",
            },
        ),
        migrations.CreateModel(
            name="ServiceModificationHistoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "fields",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50)
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUGGESTION", "Suggestion"),
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="",
                        max_length=20,
                        verbose_name="Statut après modification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de modification de service",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ServiceSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Source",
            },
        ),
        migrations.CreateModel(
            name="ServiceStatusHistoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("SUGGESTION", "Suggestion"),
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Nouveau statut",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUGGESTION", "Suggestion"),
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Statut précédent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique des statuts de service",
                "ordering": ["-date"],
                "get_latest_by": "date",
            },
        ),
        migrations.CreateModel(
            name="ServiceSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("is_obsolete", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Sous-catégorie",
            },
        ),
    ]
