# Generated by Django 6.0.2 on 2026-03-02 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("structures", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accesscondition",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="structures.structure",
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="structures.structure",
            ),
        ),
        migrations.AddField(
            model_name="francetravailorientableservice",
            name="structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orientable_ft_services_agencies",
                to="structures.structure",
            ),
        ),
        migrations.AddField(
            model_name="public",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="structures.structure",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="structures.structure",
            ),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="funding_labels",
            field=models.ManyToManyField(
                blank=True,
                to="services.fundinglabel",
                verbose_name="Labels de financement",
            ),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="location_kinds",
            field=models.ManyToManyField(
                blank=True,
                to="services.locationkind",
                verbose_name="Lieu de déroulement",
            ),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="access_conditions",
            field=models.ManyToManyField(
                blank=True,
                to="services.accesscondition",
                verbose_name="Critères d’admission",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="beneficiaries_access_modes",
            field=models.ManyToManyField(
                blank=True,
                to="services.beneficiaryaccessmode",
                verbose_name="Comment mobiliser la solution en tant que bénéficiaire",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="coach_orientation_modes",
            field=models.ManyToManyField(
                blank=True,
                to="services.coachorientationmode",
                verbose_name="Comment orienter un bénéficiaire en tant qu’accompagnateur",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="credentials",
            field=models.ManyToManyField(
                blank=True,
                to="services.credential",
                verbose_name="Quels sont les justificatifs à fournir ?",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="funding_labels",
            field=models.ManyToManyField(
                blank=True,
                to="services.fundinglabel",
                verbose_name="Labels de financement",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="last_editor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="location_kinds",
            field=models.ManyToManyField(
                blank=True,
                to="services.locationkind",
                verbose_name="Lieu de déroulement",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="publics",
            field=models.ManyToManyField(
                blank=True, to="services.public", verbose_name="Publics"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="requirements",
            field=models.ManyToManyField(
                blank=True,
                to="services.requirement",
                verbose_name="Quels sont les pré-requis ou compétences ?",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="structures.structure",
                verbose_name="Structure",
            ),
        ),
        migrations.AddField(
            model_name="francetravailorientableservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orientable_ft_services",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.service",
            ),
        ),
        migrations.CreateModel(
            name="ServiceModel",
            fields=[],
            options={
                "verbose_name": "Modèle",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("services.service",),
        ),
        migrations.AddField(
            model_name="service",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                to="services.servicecategory",
                verbose_name="Catégories principales",
            ),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.servicecategory",
                verbose_name="Thématique",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="fee_condition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="services.servicefee",
                verbose_name="Frais à charge",
            ),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="fees",
            field=models.ManyToManyField(
                blank=True, to="services.servicefee", verbose_name="Frais à charge"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="kinds",
            field=models.ManyToManyField(
                blank=True, to="services.servicekind", verbose_name="Type de service"
            ),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="kinds",
            field=models.ManyToManyField(
                blank=True, to="services.servicekind", verbose_name="Type de service"
            ),
        ),
        migrations.AddField(
            model_name="servicemodificationhistoryitem",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_item",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="servicemodificationhistoryitem",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="services.servicesource",
            ),
        ),
        migrations.AddField(
            model_name="servicestatushistoryitem",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history_item",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="servicestatushistoryitem",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True,
                to="services.servicesubcategory",
                verbose_name="Sous-catégorie",
            ),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True, to="services.servicesubcategory", verbose_name="Besoins"
            ),
        ),
        migrations.AddConstraint(
            model_name="accesscondition",
            constraint=models.UniqueConstraint(
                fields=("name", "structure"),
                name="services_unique_accesscondition_by_structure",
            ),
        ),
        migrations.AddConstraint(
            model_name="credential",
            constraint=models.UniqueConstraint(
                fields=("name", "structure"),
                name="services_unique_credential_by_structure",
            ),
        ),
        migrations.AddConstraint(
            model_name="public",
            constraint=models.UniqueConstraint(
                fields=("name", "structure"), name="services_unique_public_by_structure"
            ),
        ),
        migrations.AddConstraint(
            model_name="requirement",
            constraint=models.UniqueConstraint(
                fields=("name", "structure"),
                name="services_unique_requirement_by_structure",
            ),
        ),
        migrations.AddConstraint(
            model_name="francetravailorientableservice",
            constraint=models.UniqueConstraint(
                fields=("structure", "service"), name="unique_structure_service"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                condition=models.Q(("service__isnull", False)),
                fields=("user", "service"),
                name="services_unique_service_bookmark",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                condition=models.Q(("di_id", ""), _negated=True),
                fields=("user", "di_id"),
                name="services_unique_di_bookmark",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copies",
                to="services.servicemodel",
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_model", False), ("status__isnull", True), _connector="OR"
                ),
                name="services_service_status_not_empty_except_models",
            ),
        ),
    ]
