# Generated by Django 6.0.5 on 2026-05-21 13:17

from django.db import migrations

OLD_VALUE = "mobilite--mobilite-douce-partagee-collective"
NEW_VALUE = "mobilite--utiliser-des-services-de-mobilite-partagee"


def rename_mobilite_subcategory(apps, schema_editor):
    ServiceSubCategory = apps.get_model("services", "ServiceSubCategory")
    ServiceSubCategory.objects.filter(value=OLD_VALUE).update(value=NEW_VALUE)


def reverse_rename_mobilite_subcategory(apps, schema_editor):
    ServiceSubCategory = apps.get_model("services", "ServiceSubCategory")
    ServiceSubCategory.objects.filter(value=NEW_VALUE).update(value=OLD_VALUE)


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_seed_data"),
    ]

    operations = [
        migrations.RunPython(
            rename_mobilite_subcategory,
            reverse_code=reverse_rename_mobilite_subcategory,
        ),
    ]
