# Generated by Django 6.0.5 on 2026-07-29 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_seed_data"),
        ("structures", "0003_protect_structure_fks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesscondition",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="structures.structure",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="structures.structure",
            ),
        ),
        migrations.AlterField(
            model_name="francetravailorientableservice",
            name="structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orientable_ft_services_agencies",
                to="structures.structure",
            ),
        ),
        migrations.AlterField(
            model_name="public",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="structures.structure",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="structures.structure",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="structures.structure",
                verbose_name="Structure",
            ),
        ),
    ]
