# Generated by Django 6.0.7 on 2026-08-11 16:05

import django.contrib.postgres.fields
import dora.services.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_savedsearch_kinds_array"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="publics_di",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=255,
                    validators=[dora.services.models.validate_corresponding_di_publics],
                ),
                blank=True,
                default=list,
                verbose_name="Publics (référentiel DI)",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="publics_precisions",
            field=models.TextField(
                blank=True, default="", verbose_name="Précisions publics"
            ),
        ),
    ]
