# Generated by Django 6.0.7 on 2026-08-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_service_kinds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='use_inclusion_numerique_scheme',
        ),
    ]
