# Generated by Django 6.0.5 on 2026-08-20 09:07

import django.contrib.postgres.fields
from django.db import migrations, models


def _backfill_mobilisation_fields(apps, schema_editor):
    from dora.services.mobilisation import sync_mobilisation_fields
    from dora.services.models import Service

    for service in Service.objects.prefetch_related(
        "coach_orientation_modes",
        "beneficiaries_access_modes",
    ):
        sync_mobilisation_fields(service)


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0010_recompute_sync_checksums_publics"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="mobilisation_details",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Précisions sur la mobilisation",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="mobilisation_link",
            field=models.URLField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Lien de mobilisation",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="mobilisable_by",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=None,
                null=True,
                verbose_name="Mobilisable par",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="mobilisation_modes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=None,
                null=True,
                verbose_name="Modes de mobilisation",
            ),
        ),
        migrations.RunPython(
            _backfill_mobilisation_fields,
            migrations.RunPython.noop,
        ),
    ]
