# Generated by Django 6.0.5 on 2026-08-20 09:07

import django.contrib.postgres.fields
from django.db import migrations, models

from dora.services.mobilisation import sync_mobilisation_fields

BATCH = 500
MOBILISATION_FIELDS = [
    "mobilisation_modes",
    "mobilisable_by",
    "mobilisation_details",
    "mobilisation_link",
]


def _backfill_mobilisation_fields(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    updated = []
    # services ET models
    services = Service._base_manager.prefetch_related(
        "coach_orientation_modes",
        "beneficiaries_access_modes",
    ).iterator(chunk_size=BATCH)
    for service in services:
        sync_mobilisation_fields(service, save=False)
        updated.append(service)
        if len(updated) >= BATCH:
            Service._base_manager.bulk_update(updated, MOBILISATION_FIELDS)
            updated = []

    if updated:
        Service._base_manager.bulk_update(updated, MOBILISATION_FIELDS)


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0013_drop_publics_m2m_rename_publics_di"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="mobilisation_details",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Précisions sur la mobilisation",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="mobilisation_link",
            field=models.URLField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Lien de mobilisation",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="mobilisable_by",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=None,
                null=True,
                verbose_name="Mobilisable par",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="mobilisation_modes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=None,
                null=True,
                verbose_name="Modes de mobilisation",
            ),
        ),
        migrations.RunPython(
            _backfill_mobilisation_fields,
            migrations.RunPython.noop,
        ),
    ]
