# Generated by Django 6.0.8 on 2026-09-01 16:06

import django.contrib.postgres.fields
from django.db import migrations, models

import dora.services.models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0017_service_zone_eligibilite"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="conditions_acces",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Conditions d'accès"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="publics_derived_from_conditions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=255,
                    validators=[dora.services.models.validate_corresponding_di_publics],
                ),
                blank=True,
                default=list,
                verbose_name="Publics dérivés des conditions d'accès",
            ),
        ),
    ]
