# Generated by Django 6.1 on 2026-09-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0018_service_conditions_acces_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="horaires_accueil",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Horaires d'accueil du public",
            ),
        ),
    ]
