# Generated by Django 6.0.8 on 2026-09-16 14:52

import django.contrib.postgres.fields
from django.db import migrations, models

import dora.services.models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0019_service_horaires_accueil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="forms",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1024),
                blank=True,
                default=list,
                validators=[dora.services.models.validate_unique_form_names],
                verbose_name="Partagez les documents à compléter",
            ),
        ),
    ]
