# Generated by Django 6.0.8 on 2026-09-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0021_recompute_sync_checksums_update_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Nom de l’offre"),
        ),
    ]
