# Generated by Django 6.1.1 on 2026-09-24 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0021_recompute_sync_checksums_update_frequency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="moderation_date",
        ),
        migrations.RemoveField(
            model_name="service",
            name="moderation_status",
        ),
    ]
