# Generated by Django 6.1.1 on 2026-09-28 08:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0021_recompute_sync_checksums_update_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedsearch",
            name="kinds",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("accompagnement", "Accompagnement"),
                        ("aide-financiere", "Aide financière"),
                        ("aide-materielle", "Aide matérielle"),
                        ("atelier", "Atelier"),
                        ("formation", "Formation"),
                        ("information", "Information"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                verbose_name="Types de service",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accompagnement", "Accompagnement"),
                    ("aide-financiere", "Aide financière"),
                    ("aide-materielle", "Aide matérielle"),
                    ("atelier", "Atelier"),
                    ("formation", "Formation"),
                    ("information", "Information"),
                ],
                default=None,
                max_length=255,
                null=True,
                verbose_name="Type de service",
            ),
        ),
    ]
