# Generated by Django 6.1.1 on 2026-09-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0022_alter_savedsearch_kinds_alter_service_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Nom de l’offre"),
        ),
    ]
