# Generated by Django 6.1.1 on 2026-09-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0023_remove_service_moderation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Nom de l’offre"),
        ),
    ]
