# Generated by Django 4.2.16 on 2024-11-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0112_add_funding_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedsearch",
            name="funding_labels",
            field=models.ManyToManyField(
                blank=True,
                to="services.fundinglabel",
                verbose_name="Labels de financement",
            ),
        ),
    ]
