# Generated by Django 4.2.16 on 2024-12-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0113_savedsearch_funding_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="duration_weekly_hours",
            field=models.PositiveIntegerField(blank=True, help_text="Nombre d'heures par semaine pour effectuer ce service.", null=True, verbose_name="Temps hebdomadaire"),
        ),
        migrations.AddField(
            model_name="service",
            name="duration_weeks",
            field=models.PositiveIntegerField(blank=True, help_text="Nombre de semaines que durent le service (par défaut, 1)", null=True, verbose_name="Durée"),
        ),
    ]
