# Generated by Django 4.2.17 on 2025-01-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0114_service_duration_weekly_hours_service_duration_weeks"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="update_frequency",
            field=models.CharField(
                choices=[
                    (
                        "tous-les-mois",
                        "Très souvent, je veux recevoir une alerte tous les mois",
                    ),
                    (
                        "tous-les-3-mois",
                        "Régulièrement, je veux recevoir une alerte tous les 3 mois",
                    ),
                    (
                        "tous-les-6-mois",
                        "Occasionnellement, je veux recevoir une alerte tous les 6 mois",
                    ),
                    (
                        "tous-les-12-mois",
                        "Très rarement, je veux recevoir une alerte tous les 12 mois",
                    ),
                    (
                        "tous-les-16-mois",
                        "Presque jamais, je veux recevoir une alerte tous les 16 mois",
                    ),
                    ("jamais", "Jamais, les informations n’évoluent jamais"),
                ],
                db_index=True,
                default="tous-les-6-mois",
                max_length=16,
                verbose_name="Fréquence de mise à jour",
            ),
        ),
    ]
