# Generated by Django 4.2.19 on 2025-02-27 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0074_alter_structure_code_safir_pe_alter_structure_siret"),
        ("services", "0115_service_update_frequency"),
    ]

    operations = [
        migrations.CreateModel(
            name="FranceTravailOrientableService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orientable_ft_services",
                        to="services.service",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orientable_ft_services_agencies",
                        to="structures.structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "service France Travail orientable",
                "verbose_name_plural": "services France Travail orientables",
            },
        ),
    ]
