# Generated by Django 5.1.7 on 2025-03-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0116_francetravailorientableservice"),
        ("structures", "0074_alter_structure_code_safir_pe_alter_structure_siret"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="francetravailorientableservice",
            constraint=models.UniqueConstraint(
                fields=("structure", "service"), name="unique_structure_service"
            ),
        ),
    ]
