# Generated by Django 5.2.1 on 2025-05-27 16:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0117_francetravailorientableservice_unique_structure_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="concernedpublic",
            name="profile_families",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("adultes", "Adultes"),
                        ("alternants", "Alternants"),
                        (
                            "beneficiaires-rsa",
                            "Bénéficiaires du Revenu de Solidarité Active (RSA)",
                        ),
                        ("deficience-visuelle", "Déficience visuelle"),
                        ("demandeurs-demploi", "Demandeurs ou demandeuses d’emploi"),
                        ("familles-enfants", "Familles/enfants"),
                        ("etudiants", "Étudiants"),
                        ("femmes", "Femmes"),
                        (
                            "handicaps-mentaux",
                            "Handicaps mentaux : déficiences limitant les activités d’une personne",
                        ),
                        (
                            "handicaps-psychiques",
                            "Handicaps psychiques : troubles psychiatriques donnant lieu à des atteintes comportementales",
                        ),
                        ("jeunes", "Jeunes"),
                        ("jeunes-16-26", "Jeunes (16-26 ans)"),
                        ("locataires", "Locataires"),
                        (
                            "personnes-de-nationalite-etrangere",
                            "Personnes de nationalité étrangère",
                        ),
                        (
                            "personnes-en-situation-de-handicap",
                            "Personnes en situation de handicap",
                        ),
                        (
                            "personnes-en-situation-illettrisme",
                            "Personnes en situation d’illettrisme",
                        ),
                        ("personnes-handicapees", "Personnes handicapées"),
                        ("proprietaires", "Propriétaires"),
                        ("public-langues-etrangeres", "Public langues étrangères"),
                        ("retraites", "Retraités"),
                        ("salaries", "Salariés"),
                        ("sans-domicile-fixe", "Sans domicile fixe"),
                        ("seniors-65", "Seniors (+ 65 ans)"),
                        ("sortants-de-detention", "Sortants de détention"),
                        ("surdite", "Surdité"),
                        ("victimes", "Victimes"),
                        ("tous-publics", "Tout publics"),
                        ("personnes-en-situation-durgence", "Victimes"),
                    ],
                    max_length=255,
                ),
                null=True,
                size=None,
                verbose_name="Familles de profils",
            ),
        ),
    ]
