# Generated by Django 5.2.1 on 2025-06-10 17:10

import django.contrib.postgres.fields
from django.db import migrations, models

import dora.services.models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0118_concernedpublic_profile_families"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concernedpublic",
            name="profile_families",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=255,
                    validators=[dora.services.models.validate_profile_families],
                ),
                default=list,
                size=None,
                verbose_name="Familles de profils",
            ),
        ),
    ]
