# Generated by Django 5.2.1 on 2025-05-28 09:24

import logging

from django.db import migrations

logger = logging.getLogger(__name__)

ACCESS_CONDITION_ALLOCATAIRE_CAF = 1753  # Allocataire CAF
ACCESS_CONDITION_BENEFICIAIRE_ACCOMPAGNEMENT_PLIE = (
    1754  # Bénéficiaire d'un accompagnement PLIE
)
ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE = 1755  # Être éligible aux critères IAE
ACCESS_CONDITION_SALARIE_SIAE = 1756  # Salarié d'une SIAE
ACCESS_CONDITION_INSCRIT_MISSION_LOCALE = 1757  # Inscrit à la Mission Locale
ACCESS_CONDITION_RESIDENT_QPV_OU_ZRR = 1758  # Résident QPV / ZRR
ACCESS_CONDITION_PERSONNE_NON_IMPOSABLE = 1759  # Personne non imposable
ACCESS_CONDITION_SANS_LOGEMENT_MAL_LOGE = 1760  # Sans logement / mal logé
ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE = (
    1769  # Personnes n'ayant pas accès au crédit bancaire classique
)

PROFILE_CHANGES: dict[int, dict[str, list[int]]] = {
    # Document de travail
    54: {"newProfileIds": (1612,)},
    48: {},
    423: {},
    37: {},
    793: {},
    25: {"accessConditionIds": (ACCESS_CONDITION_PERSONNE_NON_IMPOSABLE,)},
    791: {},
    32: {"newProfileIds": (50,)},
    77: {"newProfileIds": (74,)},
    21: {},
    20: {},
    16: {"newProfileIds": (69,)},
    2: {"newProfileIds": (23,)},
    15: {"newProfileIds": (23,)},
    34: {"newProfileIds": (1612,)},
    426: {},
    11: {},
    427: {"newProfileIds": (46,)},
    76: {"newProfileIds": (46,)},
    35: {"newProfileIds": (1611,)},
    424: {"newProfileIds": (46,)},
    60: {"newProfileIds": (46,)},
    425: {"newProfileIds": (46,)},
    72: {"accessConditionIds": (ACCESS_CONDITION_RESIDENT_QPV_OU_ZRR,)},
    19: {"accessConditionIds": (ACCESS_CONDITION_RESIDENT_QPV_OU_ZRR,)},
    39: {"newProfileIds": (8,)},
    33: {},
    53: {"newProfileIds": (1615, 1616)},
    63: {},
    4: {},
    # Profils custom
    773: {},
    1193: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    339: {
        "newProfileIds": (74,),
    },
    802: {},
    881: {},
    245: {},
    935: {},
    807: {
        "newProfileIds": (18,),
    },
    218: {},
    1128: {},
    171: {"accessConditionIds": (ACCESS_CONDITION_BENEFICIAIRE_ACCOMPAGNEMENT_PLIE,)},
    1183: {},
    738: {},
    1006: {
        "newProfileIds": (1613,),
    },
    878: {"accessConditionIds": (ACCESS_CONDITION_ALLOCATAIRE_CAF,)},
    874: {"accessConditionIds": (ACCESS_CONDITION_ALLOCATAIRE_CAF,)},
    357: {
        "newProfileIds": (18,),
    },
    211: {
        "newProfileIds": (18,),
    },
    213: {
        "newProfileIds": (18,),
    },
    1026: {"accessConditionIds": (ACCESS_CONDITION_ALLOCATAIRE_CAF,)},
    1088: {
        "newProfileIds": (18,),
    },
    782: {},
    301: {},
    1067: {},
    346: {
        "newProfileIds": (46,),
    },
    977: {
        "newProfileIds": (66,),
    },
    975: {
        "newProfileIds": (66,),
    },
    848: {
        "newProfileIds": (66,),
    },
    876: {
        "newProfileIds": (66,),
    },
    978: {
        "newProfileIds": (66,),
    },
    772: {},
    976: {
        "newProfileIds": (66,),
    },
    189: {
        "newProfileIds": (1617,),
    },
    1203: {
        "newProfileIds": (18,),
    },
    1053: {
        "newProfileIds": (18,),
    },
    786: {
        "newProfileIds": (18,),
    },
    1294: {
        "newProfileIds": (18,),
    },
    252: {
        "newProfileIds": (18,),
    },
    258: {
        "newProfileIds": (18,),
    },
    1107: {
        "newProfileIds": (18,),
    },
    1160: {
        "newProfileIds": (18,),
    },
    216: {
        "newProfileIds": (18,),
    },
    1011: {},
    923: {
        "newProfileIds": (18,),
    },
    372: {"accessConditionIds": (ACCESS_CONDITION_BENEFICIAIRE_ACCOMPAGNEMENT_PLIE,)},
    1197: {"accessConditionIds": (ACCESS_CONDITION_BENEFICIAIRE_ACCOMPAGNEMENT_PLIE,)},
    370: {
        "newProfileIds": (50,),
    },
    1127: {
        "newProfileIds": (1614,),
    },
    1196: {
        "newProfileIds": (1614,),
    },
    877: {},
    147: {
        "newProfileIds": (1617,),
    },
    146: {
        "newProfileIds": (1617,),
    },
    1190: {
        "newProfileIds": (1617,),
        "accessConditionIds": (ACCESS_CONDITION_ALLOCATAIRE_CAF,),
    },
    914: {"accessConditionIds": (ACCESS_CONDITION_SALARIE_SIAE,)},
    356: {"accessConditionIds": (ACCESS_CONDITION_BENEFICIAIRE_ACCOMPAGNEMENT_PLIE,)},
    192: {"accessConditionIds": (ACCESS_CONDITION_BENEFICIAIRE_ACCOMPAGNEMENT_PLIE,)},
    1028: {
        "newProfileIds": (18,),
    },
    219: {
        "newProfileIds": (18,),
    },
    144: {
        "newProfileIds": (18,),
    },
    145: {
        "newProfileIds": (18,),
    },
    1145: {
        "newProfileIds": (18,),
    },
    1162: {
        "newProfileIds": (18,),
    },
    1163: {
        "newProfileIds": (18,),
    },
    1161: {
        "newProfileIds": (18,),
    },
    445: {
        "newProfileIds": (1611,),
    },
    1024: {
        "newProfileIds": (1611,),
    },
    231: {
        "newProfileIds": (1611,),
    },
    633: {
        "newProfileIds": (1611,),
    },
    624: {
        "newProfileIds": (1611,),
    },
    621: {
        "newProfileIds": (1611,),
    },
    619: {
        "newProfileIds": (1611,),
    },
    617: {
        "newProfileIds": (1611,),
    },
    615: {
        "newProfileIds": (1611,),
    },
    613: {
        "newProfileIds": (1611,),
    },
    611: {
        "newProfileIds": (1611,),
    },
    609: {
        "newProfileIds": (1611,),
    },
    607: {
        "newProfileIds": (1611,),
    },
    605: {
        "newProfileIds": (1611,),
    },
    603: {
        "newProfileIds": (1611,),
    },
    601: {
        "newProfileIds": (1611,),
    },
    599: {
        "newProfileIds": (1611,),
    },
    597: {
        "newProfileIds": (1611,),
    },
    595: {
        "newProfileIds": (1611,),
    },
    593: {
        "newProfileIds": (1611,),
    },
    591: {
        "newProfileIds": (1611,),
    },
    589: {
        "newProfileIds": (1611,),
    },
    587: {
        "newProfileIds": (1611,),
    },
    585: {
        "newProfileIds": (1611,),
    },
    1535: {
        "newProfileIds": (1611,),
    },
    1573: {
        "newProfileIds": (1611,),
    },
    583: {
        "newProfileIds": (1611,),
    },
    1539: {
        "newProfileIds": (1611,),
    },
    581: {
        "newProfileIds": (1611,),
    },
    579: {
        "newProfileIds": (1611,),
    },
    577: {
        "newProfileIds": (1611,),
    },
    575: {
        "newProfileIds": (1611,),
    },
    573: {
        "newProfileIds": (1611,),
    },
    1537: {
        "newProfileIds": (1611,),
    },
    571: {
        "newProfileIds": (1611,),
    },
    569: {
        "newProfileIds": (1611,),
    },
    567: {
        "newProfileIds": (1611,),
    },
    565: {
        "newProfileIds": (1611,),
    },
    563: {
        "newProfileIds": (1611,),
    },
    561: {
        "newProfileIds": (1611,),
    },
    559: {
        "newProfileIds": (1611,),
    },
    557: {
        "newProfileIds": (1611,),
    },
    555: {
        "newProfileIds": (1611,),
    },
    553: {
        "newProfileIds": (1611,),
    },
    551: {
        "newProfileIds": (1611,),
    },
    549: {
        "newProfileIds": (1611,),
    },
    547: {
        "newProfileIds": (1611,),
    },
    545: {
        "newProfileIds": (1611,),
    },
    543: {
        "newProfileIds": (1611,),
    },
    541: {
        "newProfileIds": (1611,),
    },
    539: {
        "newProfileIds": (1611,),
    },
    537: {
        "newProfileIds": (1611,),
    },
    535: {
        "newProfileIds": (1611,),
    },
    533: {
        "newProfileIds": (1611,),
    },
    1288: {
        "newProfileIds": (1611,),
    },
    531: {
        "newProfileIds": (1611,),
    },
    529: {
        "newProfileIds": (1611,),
    },
    527: {
        "newProfileIds": (1611,),
    },
    525: {
        "newProfileIds": (1611,),
    },
    523: {
        "newProfileIds": (1611,),
    },
    521: {
        "newProfileIds": (1611,),
    },
    519: {
        "newProfileIds": (1611,),
    },
    517: {
        "newProfileIds": (1611,),
    },
    515: {
        "newProfileIds": (1611,),
    },
    513: {
        "newProfileIds": (1611,),
    },
    511: {
        "newProfileIds": (1611,),
    },
    509: {
        "newProfileIds": (1611,),
    },
    507: {
        "newProfileIds": (1611,),
    },
    505: {
        "newProfileIds": (1611,),
    },
    503: {
        "newProfileIds": (1611,),
    },
    501: {
        "newProfileIds": (1611,),
    },
    499: {
        "newProfileIds": (1611,),
    },
    497: {
        "newProfileIds": (1611,),
    },
    495: {
        "newProfileIds": (1611,),
    },
    493: {
        "newProfileIds": (1611,),
    },
    491: {
        "newProfileIds": (1611,),
    },
    489: {
        "newProfileIds": (1611,),
    },
    487: {
        "newProfileIds": (1611,),
    },
    485: {
        "newProfileIds": (1611,),
    },
    483: {
        "newProfileIds": (1611,),
    },
    481: {
        "newProfileIds": (1611,),
    },
    479: {
        "newProfileIds": (1611,),
    },
    477: {
        "newProfileIds": (1611,),
    },
    475: {
        "newProfileIds": (1611,),
    },
    473: {
        "newProfileIds": (1611,),
    },
    471: {
        "newProfileIds": (1611,),
    },
    469: {
        "newProfileIds": (1611,),
    },
    467: {
        "newProfileIds": (1611,),
    },
    465: {
        "newProfileIds": (1611,),
    },
    463: {
        "newProfileIds": (1611,),
    },
    461: {
        "newProfileIds": (1611,),
    },
    433: {
        "newProfileIds": (1611,),
    },
    459: {
        "newProfileIds": (1611,),
    },
    435: {
        "newProfileIds": (1611,),
    },
    457: {
        "newProfileIds": (1611,),
    },
    437: {
        "newProfileIds": (1611,),
    },
    455: {
        "newProfileIds": (1611,),
    },
    439: {
        "newProfileIds": (1611,),
    },
    453: {
        "newProfileIds": (1611,),
    },
    441: {
        "newProfileIds": (1611,),
    },
    451: {
        "newProfileIds": (1611,),
    },
    443: {
        "newProfileIds": (1611,),
    },
    449: {
        "newProfileIds": (1611,),
    },
    447: {
        "newProfileIds": (1611,),
    },
    1280: {
        "newProfileIds": (1614,),
    },
    428: {
        "newProfileIds": (1614,),
    },
    1276: {
        "newProfileIds": (1614,),
    },
    941: {
        "newProfileIds": (1614,),
    },
    1273: {
        "newProfileIds": (1614,),
    },
    1241: {
        "newProfileIds": (1614,),
    },
    364: {
        "newProfileIds": (1614,),
    },
    1267: {
        "newProfileIds": (1614,),
    },
    1269: {
        "newProfileIds": (1614,),
    },
    151: {
        "newProfileIds": (1617,),
    },
    1055: {
        "newProfileIds": (1617,),
    },
    1063: {
        "newProfileIds": (1617,),
    },
    1215: {"accessConditionIds": (ACCESS_CONDITION_SALARIE_SIAE,)},
    383: {
        "newProfileIds": (18,),
    },
    1085: {
        "newProfileIds": (18,),
    },
    380: {
        "newProfileIds": (18,),
    },
    901: {
        "newProfileIds": (18,),
    },
    685: {
        "newProfileIds": (18,),
    },
    801: {
        "newProfileIds": (18,),
    },
    910: {
        "newProfileIds": (18,),
    },
    273: {
        "newProfileIds": (18,),
    },
    1058: {},
    379: {
        "newProfileIds": (18,),
    },
    1050: {},
    728: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    302: {},
    1115: {},
    224: {},
    225: {},
    1200: {
        "newProfileIds": (1607,),
    },
    172: {
        "newProfileIds": (1607,),
    },
    214: {
        "newProfileIds": (1607,),
    },
    269: {
        "newProfileIds": (50,),
    },
    1218: {
        "newProfileIds": (1608,),
    },
    1147: {
        "newProfileIds": (1607,),
    },
    150: {
        "newProfileIds": (50,),
    },
    1167: {
        "newProfileIds": (50,),
    },
    208: {
        "newProfileIds": (1607,),
    },
    883: {
        "newProfileIds": (1607,),
    },
    986: {
        "newProfileIds": (1608,),
    },
    907: {
        "newProfileIds": (1608,),
    },
    1086: {
        "newProfileIds": (1607,),
    },
    989: {
        "newProfileIds": (50,),
    },
    1002: {
        "newProfileIds": (1607,),
    },
    993: {
        "newProfileIds": (1607,),
    },
    985: {
        "newProfileIds": (1607,),
    },
    263: {
        "newProfileIds": (1608,),
    },
    262: {
        "newProfileIds": (1608,),
    },
    141: {
        "newProfileIds": (41,),
    },
    143: {
        "newProfileIds": (41,),
    },
    994: {
        "newProfileIds": (1608,),
    },
    253: {
        "newProfileIds": (50,),
    },
    679: {
        "newProfileIds": (50,),
    },
    903: {
        "newProfileIds": (50,),
    },
    1233: {
        "newProfileIds": (
            50,
            28,
        ),
    },
    898: {
        "newProfileIds": (50,),
    },
    1252: {
        "newProfileIds": (50,),
    },
    1097: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    1140: {},
    1139: {
        "newProfileIds": (50,),
    },
    628: {},
    1176: {},
    778: {},
    212: {},
    1052: {},
    1133: {},
    283: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    282: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    927: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    916: {"accessConditionIds": (ACCESS_CONDITION_BENEFICIAIRE_ACCOMPAGNEMENT_PLIE,)},
    920: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    281: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    376: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    1174: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    752: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    259: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    767: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    1289: {},
    226: {},
    220: {},
    221: {},
    222: {},
    402: {},
    401: {},
    1178: {
        "newProfileIds": (
            8,
            18,
        ),
    },
    675: {},
    300: {},
    629: {},
    1066: {},
    1199: {"accessConditionIds": (ACCESS_CONDITION_BENEFICIAIRE_ACCOMPAGNEMENT_PLIE,)},
    884: {},
    846: {"accessConditionIds": (ACCESS_CONDITION_ALLOCATAIRE_CAF,)},
    847: {
        "newProfileIds": (38,),
    },
    1091: {},
    1090: {},
    1098: {},
    917: {},
    777: {},
    857: {
        "newProfileIds": (47,),
    },
    860: {
        "newProfileIds": (47,),
    },
    863: {
        "newProfileIds": (47,),
    },
    866: {
        "newProfileIds": (47,),
    },
    869: {
        "newProfileIds": (47,),
    },
    922: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    1076: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    296: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    375: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    157: {
        "newProfileIds": (
            69,
            52,
        ),
    },
    400: {
        "newProfileIds": (69,),
    },
    1065: {
        "newProfileIds": (69,),
    },
    294: {
        "newProfileIds": (67,),
        "accessConditionIds": (ACCESS_CONDITION_ALLOCATAIRE_CAF,),
    },
    95: {},
    81: {},
    1278: {
        "newProfileIds": (67,),
    },
    787: {
        "newProfileIds": (792,),
    },
    669: {
        "newProfileIds": (792,),
    },
    761: {
        "newProfileIds": (792,),
    },
    769: {
        "newProfileIds": (792,),
    },
    623: {
        "newProfileIds": (792,),
    },
    762: {
        "newProfileIds": (792,),
    },
    1072: {
        "newProfileIds": (
            5,
            6,
        ),
    },
    1073: {},
    385: {
        "newProfileIds": (
            1617,
            792,
        ),
    },
    250: {
        "newProfileIds": (5,),
    },
    1165: {
        "newProfileIds": (5,),
    },
    1012: {},
    264: {
        "newProfileIds": (
            66,
            67,
        ),
    },
    1069: {},
    387: {},
    1071: {},
    388: {},
    775: {},
    167: {},
    763: {},
    176: {"accessConditionIds": (ACCESS_CONDITION_RESIDENT_QPV_OU_ZRR,)},
    1032: {},
    180: {
        "newProfileIds": (
            1617,
            5,
        ),
    },
    886: {"accessConditionIds": (ACCESS_CONDITION_INSCRIT_MISSION_LOCALE,)},
    885: {"accessConditionIds": (ACCESS_CONDITION_INSCRIT_MISSION_LOCALE,)},
    389: {
        "newProfileIds": (1,),
    },
    396: {},
    1111: {},
    760: {"accessConditionIds": (ACCESS_CONDITION_INSCRIT_MISSION_LOCALE,)},
    293: {
        "newProfileIds": (47,),
    },
    251: {},
    932: {},
    934: {},
    391: {},
    210: {},
    217: {
        "newProfileIds": (18,),
    },
    990: {
        "newProfileIds": (18,),
    },
    991: {
        "newProfileIds": (18,),
    },
    1155: {},
    240: {
        "newProfileIds": (
            65,
            1615,
        ),
    },
    1082: {},
    1106: {
        "newProfileIds": (6,),
    },
    683: {},
    794: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    205: {
        "newProfileIds": (46,),
    },
    270: {},
    201: {},
    1132: {
        "newProfileIds": (66,),
    },
    1187: {
        "newProfileIds": (66,),
    },
    1004: {},
    630: {},
    1168: {"accessConditionIds": (ACCESS_CONDITION_BENEFICIAIRE_ACCOMPAGNEMENT_PLIE,)},
    352: {},
    1212: {},
    1211: {},
    1217: {},
    799: {"accessConditionIds": (ACCESS_CONDITION_SALARIE_SIAE,)},
    369: {},
    184: {},
    798: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    1038: {},
    795: {"accessConditionIds": (ACCESS_CONDITION_SALARIE_SIAE,)},
    746: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    800: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    797: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    783: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    361: {"accessConditionIds": (ACCESS_CONDITION_SANS_LOGEMENT_MAL_LOGE,)},
    929: {"accessConditionIds": (ACCESS_CONDITION_SANS_LOGEMENT_MAL_LOGE,)},
    148: {
        "newProfileIds": (1,),
    },
    195: {},
    237: {"accessConditionIds": (ACCESS_CONDITION_SALARIE_SIAE,)},
    1030: {},
    1039: {},
    1105: {
        "newProfileIds": (46,),
    },
    1221: {},
    200: {},
    168: {"accessConditionIds": (ACCESS_CONDITION_BENEFICIAIRE_ACCOMPAGNEMENT_PLIE,)},
    911: {},
    796: {},
    1198: {},
    1283: {},
    1286: {},
    1095: {},
    199: {},
    349: {
        "newProfileIds": (46,),
    },
    1020: {},
    188: {},
    737: {},
    1392: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1391: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1399: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1400: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1390: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1389: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1388: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1401: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1402: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1403: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1404: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1405: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1460: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1387: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1338: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1406: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1386: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1385: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1333: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1339: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1407: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1384: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1332: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1383: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1340: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1382: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1331: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1341: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    808: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1330: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1054: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1408: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1342: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1329: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1409: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1501: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1315: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1396: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1335: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1395: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1337: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1334: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1398: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1394: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    280: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1393: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1317: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1445: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1446: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1447: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1448: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1354: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1449: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1318: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1353: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1351: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1450: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1451: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1320: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1452: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1319: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1352: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1453: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1454: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1410: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1411: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1397: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1462: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1412: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1459: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1413: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1461: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1380: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1414: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1415: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1343: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1458: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1457: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1379: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1378: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1377: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1376: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1328: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1456: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1416: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1344: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1417: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1375: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1374: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1327: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1418: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1345: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1326: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1373: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1346: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1325: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1419: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1420: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1421: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1422: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1423: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1347: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1372: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1324: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1424: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1425: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1371: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1426: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1427: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1370: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1369: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1428: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1368: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1348: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1367: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1323: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1366: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1429: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1300: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1322: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1301: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1430: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1349: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1365: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1302: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1431: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1432: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1364: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1303: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1336: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1433: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1304: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1363: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1305: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1321: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1434: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1435: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1306: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1436: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1362: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1307: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1361: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1308: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1360: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1309: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1437: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1359: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1310: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1438: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1455: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1358: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1439: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1311: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1440: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1441: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1312: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1313: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1314: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1442: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1443: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1357: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1444: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1356: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1316: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    1355: {
        "accessConditionIds": (
            ACCESS_CONDITION_PERSONNE_N_AYANT_PAS_ACCES_AU_CREDIT_BANCAIRE_CLASSIQUE,
        )
    },
    890: {},
    1201: {},
    789: {"accessConditionIds": (ACCESS_CONDITION_SALARIE_SIAE,)},
    207: {},
    351: {},
    1056: {"accessConditionIds": (ACCESS_CONDITION_SANS_LOGEMENT_MAL_LOGE,)},
    1064: {"accessConditionIds": (ACCESS_CONDITION_SANS_LOGEMENT_MAL_LOGE,)},
    1057: {},
    1150: {},
    373: {},
    374: {},
    770: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    915: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    909: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    382: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    393: {},
    238: {
        "newProfileIds": (
            1611,
            18,
        ),
    },
    360: {
        "newProfileIds": (46,),
    },
    1159: {
        "newProfileIds": (18,),
    },
    1113: {
        "newProfileIds": (18,),
    },
    1015: {
        "newProfileIds": (18,),
    },
    1017: {
        "newProfileIds": (18,),
    },
    344: {
        "newProfileIds": (18,),
    },
    142: {
        "newProfileIds": (18,),
    },
    1096: {
        "newProfileIds": (18,),
    },
    1158: {
        "newProfileIds": (18,),
    },
    265: {
        "newProfileIds": (18,),
    },
    730: {
        "newProfileIds": (
            50,
            18,
        ),
    },
    668: {},
    850: {},
    678: {},
    1029: {},
    735: {
        "newProfileIds": (792,),
    },
    355: {"accessConditionIds": (ACCESS_CONDITION_SALARIE_SIAE,)},
    906: {},
    1222: {},
    1094: {},
    830: {},
    812: {},
    813: {},
    814: {},
    815: {},
    816: {},
    817: {},
    818: {},
    819: {},
    820: {},
    821: {},
    822: {},
    823: {},
    824: {},
    825: {},
    826: {},
    827: {},
    727: {},
    828: {},
    829: {},
    832: {},
    833: {},
    834: {},
    835: {},
    836: {},
    837: {},
    838: {},
    839: {},
    841: {},
    842: {},
    843: {},
    844: {},
    845: {},
    851: {},
    853: {},
    879: {},
    1463: {},
    1464: {},
    1465: {},
    1466: {},
    1467: {},
    1213: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    1214: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    284: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    849: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    889: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    244: {},
    260: {},
    892: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    1151: {
        "newProfileIds": (18,),
    },
    674: {},
    417: {},
    672: {},
    673: {},
    429: {},
    177: {},
    1031: {
        "newProfileIds": (
            1615,
            1616,
        ),
    },
    1126: {
        "newProfileIds": (1614,),
    },
    1272: {
        "newProfileIds": (1614,),
    },
    1195: {
        "newProfileIds": (1614,),
    },
    635: {
        "newProfileIds": (1614,),
    },
    1268: {
        "newProfileIds": (1614,),
    },
    1266: {
        "newProfileIds": (1614,),
    },
    687: {
        "newProfileIds": (1614,),
    },
    363: {
        "newProfileIds": (1614,),
    },
    430: {},
    1016: {},
    399: {},
    689: {"accessConditionIds": (ACCESS_CONDITION_RESIDENT_QPV_OU_ZRR,)},
    924: {"accessConditionIds": (ACCESS_CONDITION_RESIDENT_QPV_OU_ZRR,)},
    394: {},
    395: {},
    83: {},
    82: {},
    865: {},
    868: {},
    862: {},
    859: {},
    856: {},
    182: {},
    759: {},
    764: {},
    185: {
        "newProfileIds": (52,),
    },
    1144: {
        "newProfileIds": (52,),
    },
    1534: {
        "newProfileIds": (18,),
        "accessConditionIds": (ACCESS_CONDITION_SALARIE_SIAE,),
    },
    277: {
        "newProfileIds": (18,),
        "accessConditionIds": (ACCESS_CONDITION_SALARIE_SIAE,),
    },
    162: {
        "newProfileIds": (
            65,
            1615,
        ),
    },
    371: {"accessConditionIds": (ACCESS_CONDITION_SALARIE_SIAE,)},
    745: {"accessConditionIds": (ACCESS_CONDITION_SALARIE_SIAE,)},
    272: {"accessConditionIds": (ACCESS_CONDITION_SALARIE_SIAE,)},
    234: {
        "newProfileIds": (62,),
    },
    233: {
        "newProfileIds": (64,),
    },
    163: {
        "newProfileIds": (
            65,
            1,
            23,
        ),
    },
    338: {"accessConditionIds": (ACCESS_CONDITION_SALARIE_SIAE,)},
    190: {"accessConditionIds": (ACCESS_CONDITION_SALARIE_SIAE,)},
    243: {"accessConditionIds": (ACCESS_CONDITION_SALARIE_SIAE,)},
    229: {},
    227: {},
    228: {},
    230: {},
    1149: {},
    928: {
        "newProfileIds": (47,),
    },
    169: {},
    1295: {},
    353: {},
    390: {},
    181: {
        "newProfileIds": (1617,),
    },
    1234: {},
    1235: {},
    140: {},
    1175: {},
    1177: {},
    1087: {},
    278: {},
    410: {},
    206: {},
    937: {},
    261: {},
    1296: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    900: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    997: {},
    1036: {},
    1297: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    254: {},
    156: {},
    1292: {},
    1262: {},
    1263: {},
    1238: {},
    1240: {},
    1239: {},
    913: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    980: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    1089: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    919: {},
    1019: {},
    1135: {},
    998: {},
    751: {},
    183: {},
    872: {},
    1206: {},
    1061: {},
    1021: {},
    404: {},
    403: {},
    926: {
        "newProfileIds": (1611,),
    },
    1005: {
        "newProfileIds": (1612,),
    },
    1010: {
        "newProfileIds": (1612,),
    },
    198: {
        "newProfileIds": (1611,),
    },
    741: {},
    743: {},
    742: {},
    405: {},
    774: {},
    236: {},
    1255: {
        "newProfileIds": (8,),
    },
    1236: {"accessConditionIds": (ACCESS_CONDITION_ALLOCATAIRE_CAF,)},
    419: {
        "newProfileIds": (22,),
    },
    694: {
        "newProfileIds": (1614,),
    },
    275: {
        "newProfileIds": (1614,),
    },
    155: {
        "newProfileIds": (1617,),
    },
    153: {
        "newProfileIds": (1617,),
    },
    939: {
        "newProfileIds": (1614,),
    },
    1092: {
        "newProfileIds": (50,),
    },
    1166: {
        "newProfileIds": (1607,),
    },
    154: {
        "newProfileIds": (50,),
    },
    152: {
        "newProfileIds": (50,),
    },
    178: {
        "newProfileIds": (1607,),
    },
    413: {
        "newProfileIds": (50,),
    },
    1229: {
        "newProfileIds": (50,),
    },
    1182: {
        "newProfileIds": (50,),
    },
    1208: {},
    474: {},
    634: {},
    625: {},
    622: {},
    620: {},
    618: {},
    616: {},
    614: {},
    612: {},
    610: {},
    608: {},
    606: {},
    604: {},
    602: {},
    600: {},
    598: {},
    596: {},
    594: {},
    592: {},
    590: {},
    588: {},
    586: {},
    584: {},
    582: {},
    580: {},
    578: {},
    576: {},
    574: {},
    572: {},
    570: {},
    568: {},
    566: {},
    564: {},
    562: {},
    560: {},
    558: {},
    556: {},
    554: {},
    552: {},
    550: {},
    548: {},
    546: {},
    544: {},
    542: {},
    540: {},
    538: {},
    536: {},
    534: {},
    532: {},
    530: {},
    528: {},
    526: {},
    524: {},
    522: {},
    520: {},
    518: {},
    516: {},
    514: {},
    512: {},
    510: {},
    508: {},
    506: {},
    504: {},
    502: {},
    500: {},
    498: {},
    496: {},
    494: {},
    492: {},
    490: {},
    488: {},
    486: {},
    484: {},
    482: {},
    480: {},
    478: {},
    476: {},
    472: {},
    470: {},
    468: {},
    466: {},
    464: {},
    462: {},
    460: {},
    458: {},
    456: {},
    454: {},
    452: {},
    450: {},
    448: {},
    446: {},
    444: {},
    442: {},
    440: {},
    438: {},
    436: {},
    434: {},
    1536: {},
    1572: {},
    232: {},
    1025: {},
    1538: {},
    1574: {},
    239: {},
    1192: {},
    297: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    981: {
        "newProfileIds": (67,),
        "accessConditionIds": (ACCESS_CONDITION_ALLOCATAIRE_CAF,),
    },
    377: {
        "newProfileIds": (67,),
        "accessConditionIds": (ACCESS_CONDITION_ALLOCATAIRE_CAF,),
    },
    895: {
        "newProfileIds": (67,),
        "accessConditionIds": (ACCESS_CONDITION_ALLOCATAIRE_CAF,),
    },
    894: {
        "newProfileIds": (67,),
        "accessConditionIds": (ACCESS_CONDITION_ALLOCATAIRE_CAF,),
    },
    367: {},
    1275: {
        "newProfileIds": (47,),
    },
    1271: {
        "newProfileIds": (47,),
    },
    432: {
        "newProfileIds": (47,),
    },
    202: {
        "newProfileIds": (28,),
    },
    780: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    1003: {},
    781: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    290: {},
    729: {},
    788: {},
    779: {},
    790: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    938: {
        "newProfileIds": (1614,),
    },
    676: {},
    1250: {},
    893: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    249: {"accessConditionIds": (ACCESS_CONDITION_SALARIE_SIAE,)},
    1202: {"accessConditionIds": (ACCESS_CONDITION_SALARIE_SIAE,)},
    1009: {},
    1008: {},
    271: {},
    412: {},
    223: {},
    289: {},
    303: {},
    406: {},
    164: {
        "newProfileIds": (23,),
    },
    1207: {"accessConditionIds": (ACCESS_CONDITION_BENEFICIAIRE_ACCOMPAGNEMENT_PLIE,)},
    411: {
        "newProfileIds": (50,),
    },
    888: {"accessConditionIds": (ACCESS_CONDITION_ALLOCATAIRE_CAF,)},
    235: {},
    1157: {},
    921: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    1246: {
        "newProfileIds": (50,),
    },
}


def clean_profiles(apps, schema_editor):
    AccessCondition = apps.get_model("services", "AccessCondition")
    ConcernedPublic = apps.get_model("services", "ConcernedPublic")
    Service = apps.get_model("services", "Service")
    ServiceModel = apps.get_model("services", "ServiceModel")

    for old_profile_id, profile_changes in PROFILE_CHANGES.items():
        try:
            # Start a new transaction for each profile
            with schema_editor.connection.cursor() as cursor:
                cursor.execute("BEGIN")
                try:
                    logger.info("Traitement de l'ancien profil %d", old_profile_id)
                    old_profile = ConcernedPublic.objects.get(id=old_profile_id)

                    services = Service.objects.filter(concerned_public=old_profile)
                    service_models = ServiceModel.objects.filter(
                        concerned_public=old_profile
                    )

                    if "newProfileIds" in profile_changes:
                        logger.info(
                            "Assignation des nouveaux profils %s",
                            profile_changes["newProfileIds"],
                        )
                        new_profiles = ConcernedPublic.objects.filter(
                            id__in=profile_changes["newProfileIds"]
                        )
                        if new_profiles.count() != len(
                            profile_changes["newProfileIds"]
                        ):
                            unfound_profile_ids = set(
                                profile_changes["newProfileIds"]
                            ) - set(new_profiles.values_list("id", flat=True))
                            raise ConcernedPublic.DoesNotExist(
                                f"un ou plusieurs publics concernés non trouvés : {unfound_profile_ids}"
                            )

                        for service in services:
                            service.concerned_public.remove(old_profile)
                            service.concerned_public.add(*new_profiles)

                        for service_model in service_models:
                            service_model.concerned_public.remove(old_profile)
                            service_model.concerned_public.add(*new_profiles)

                    if "accessConditionIds" in profile_changes:
                        logger.info(
                            "Assignation des conditions d'accès %s",
                            profile_changes["accessConditionIds"],
                        )
                        access_conditions = AccessCondition.objects.filter(
                            id__in=profile_changes["accessConditionIds"]
                        )
                        if (
                            not access_conditions.exists()
                            or access_conditions.count()
                            != len(profile_changes["accessConditionIds"])
                        ):
                            raise AccessCondition.DoesNotExist(
                                f"une ou plusieures conditions d'accès non trouvées : {profile_changes['accessConditionIds']}"
                            )

                        for service in services:
                            service.access_conditions.add(*access_conditions)
                            if (
                                ACCESS_CONDITION_RESIDENT_QPV_OU_ZRR
                                in profile_changes["accessConditionIds"]
                            ):
                                service.qpv_or_zrr = True
                                service.save()

                        for service_model in service_models:
                            service_model.access_conditions.add(*access_conditions)
                            if (
                                ACCESS_CONDITION_RESIDENT_QPV_OU_ZRR
                                in profile_changes["accessConditionIds"]
                            ):
                                service_model.qpv_or_zrr = True
                                service_model.save()

                    logger.info("Suppression de l'ancien profil %d", old_profile_id)
                    old_profile.delete()

                    # If everything went well, commit the transaction
                    cursor.execute("COMMIT")
                except Exception as e:
                    # If there was an error, rollback this profile's transaction
                    cursor.execute("ROLLBACK")
                    logger.warning(
                        "Une erreur est survenue lors du traitement du profil %d : %s",
                        old_profile_id,
                        str(e),
                    )
                    # Continue with the next profile
                    continue
        except Exception as e:
            # This outer try-except is for any errors in transaction management
            logger.error(
                "Erreur de transaction pour le profil %d : %s",
                old_profile_id,
                str(e),
            )
            continue


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0119_alter_concernedpublic_profile_families"),
    ]

    operations = [
        migrations.RunPython(clean_profiles, reverse_code=migrations.RunPython.noop),
    ]
