# Generated by Django 5.2.3 on 2025-06-26 13:32

import logging

from data_inclusion.schema.v0 import Profil
from django.db import migrations

logger = logging.getLogger(__name__)

PROFILES_TO_FAMILIES = {
    1: (Profil.ACTIFS),
    2: (Profil.JEUNES, Profil.ETUDIANTS, Profil.ACTIFS),
    3: (Profil.ACTIFS),
    4: (),
    5: (Profil.FEMMES),
    6: (Profil.FAMILLES_ENFANTS),
    8: (Profil.ACTIFS, Profil.DEMANDEURS_EMPLOI, Profil.AUTRES),
    9: (Profil.DEMANDEURS_EMPLOI, Profil.BENEFICIAIRES_MINIMA_SOCIAUX),
    10: (Profil.DEMANDEURS_EMPLOI),
    11: (
        Profil.PERSONNE_EN_SITUATION_DURGENCE,
        Profil.PERSONNE_EN_SITUATION_JURIDIQUE_SPECIFIQUE,
    ),
    14: (Profil.DEMANDEURS_EMPLOI),
    15: (Profil.JEUNES, Profil.ETUDIANTS, Profil.ACTIFS),
    16: (Profil.JEUNES, Profil.ETUDIANTS),
    18: (Profil.BENEFICIAIRES_MINIMA_SOCIAUX),
    19: (Profil.RESIDENT_QPV_OU_ZRR),
    20: (Profil.JEUNES, Profil.ETUDIANTS),
    21: (Profil.JEUNES, Profil.BENEFICIAIRES_MINIMA_SOCIAUX),
    22: (Profil.ACTIFS),
    23: (Profil.ETUDIANTS, Profil.ACTIFS),
    24: (Profil.AUTRES),
    25: (Profil.AUTRES),
    26: (Profil.BENEFICIAIRES_MINIMA_SOCIAUX),
    27: (Profil.PERSONNE_EN_SITUATION_DURGENCE),
    28: (Profil.PERSONNES_EXILEES),
    29: (
        Profil.BENEFICIAIRES_MINIMA_SOCIAUX,
        Profil.PERSONNES_EN_SITUATION_DE_HANDICAP,
    ),
    30: (),
    31: (Profil.ACTIFS),
    32: (Profil.DEMANDEURS_EMPLOI),
    33: (),
    34: (Profil.JEUNES, Profil.PERSONNE_EN_SITUATION_JURIDIQUE_SPECIFIQUE),
    35: (Profil.PERSONNES_EN_SITUATION_DE_HANDICAP),
    36: (Profil.SENIORS_65),
    37: (Profil.AUTRES),
    38: (Profil.FAMILLES_ENFANTS),
    39: (),
    40: (Profil.DEMANDEURS_EMPLOI),
    41: (Profil.DEMANDEURS_EMPLOI),
    42: (Profil.ETUDIANTS),
    43: (Profil.ETUDIANTS),
    45: (Profil.DEMANDEURS_EMPLOI, Profil.ACTIFS),
    46: (Profil.PERSONNES_EN_SITUATION_DE_HANDICAP),
    47: (Profil.JEUNES),
    48: (Profil.AUTRES),
    50: (Profil.DEMANDEURS_EMPLOI),
    51: (Profil.JEUNES),
    52: (Profil.ACTIFS),
    53: (),
    54: (Profil.ACTIFS),
    56: (Profil.SENIORS_65),
    58: (Profil.PERSONNES_EN_SITUATION_DE_HANDICAP),
    60: (Profil.PERSONNES_EN_SITUATION_DE_HANDICAP),
    61: (Profil.JEUNES),
    62: (Profil.ACTIFS),
    63: (),
    64: (Profil.ACTIFS),
    65: (Profil.ACTIFS),
    66: (Profil.FAMILLES_ENFANTS),
    67: (Profil.FAMILLES_ENFANTS),
    68: (Profil.JEUNES),
    69: (Profil.ETUDIANTS),
    70: (Profil.JEUNES),
    71: (Profil.DEMANDEURS_EMPLOI),
    72: (Profil.RESIDENT_QPV_OU_ZRR),
    73: (Profil.JEUNES),
    74: (Profil.JEUNES),
    75: (Profil.JEUNES, Profil.FAMILLES_ENFANTS),
    76: (Profil.PERSONNES_EN_SITUATION_DE_HANDICAP),
    77: (Profil.JEUNES),
    420: (Profil.SENIORS_65),
    422: (Profil.JEUNES),
    423: (Profil.AUTRES),
    424: (Profil.PERSONNES_EN_SITUATION_DE_HANDICAP),
    425: (Profil.PERSONNES_EN_SITUATION_DE_HANDICAP),
    426: (Profil.PERSONNE_EN_SITUATION_DURGENCE),
    427: (Profil.PERSONNES_EN_SITUATION_DE_HANDICAP),
    791: (Profil.AUTRES),
    792: (Profil.FEMMES),
    793: (Profil.AUTRES),
    1607: (Profil.DEMANDEURS_EMPLOI),
    1608: (Profil.DEMANDEURS_EMPLOI),
    1610: (Profil.BENEFICIAIRES_MINIMA_SOCIAUX),
    1611: (Profil.PERSONNES_EN_SITUATION_DE_HANDICAP),
    1612: (Profil.ACTIFS),
    1613: (Profil.ACTIFS),
    1614: (Profil.PERSONNE_EN_SITUATION_JURIDIQUE_SPECIFIQUE),
    1615: (Profil.ACTIFS),
    1616: (Profil.ACTIFS),
    1617: (Profil.BENEFICIAIRES_MINIMA_SOCIAUX),
    1618: (Profil.PERSONNE_EN_SITUATION_JURIDIQUE_SPECIFIQUE),
}


def assign_families_to_profiles(apps, _schema_editor):
    ConcernedPublic = apps.get_model("services", "ConcernedPublic")

    for profile_id, families in PROFILES_TO_FAMILIES.items():
        try:
            profile = ConcernedPublic.objects.get(id=profile_id)
            profile.families.set(families)
            profile.save()
        except ConcernedPublic.DoesNotExist:
            logger.error("Le profil %d n'a pas été trouvé", profile_id)


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0120_clean_profiles"),
    ]

    operations = [
        migrations.RunPython(
            assign_families_to_profiles, reverse_code=migrations.RunPython.noop
        ),
    ]
