# Generated by Django 5.2.6 on 2025-09-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0121_assign_profiles_to_families"),
        ("structures", "0075_nodoraformdistructure"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConcernedPublic",
            new_name="Public",
        ),
        migrations.AlterModelOptions(
            name="public",
            options={"verbose_name": "Public", "verbose_name_plural": "Publics"},
        ),
        migrations.RemoveConstraint(
            model_name="public",
            name="services_unique_concernedpublic_by_structure",
        ),
        migrations.AddConstraint(
            model_name="public",
            constraint=models.UniqueConstraint(
                fields=("name", "structure"), name="services_unique_public_by_structure"
            ),
        ),
    ]
