# Generated by Django 5.2.6 on 2025-09-11 09:02

import django.contrib.postgres.fields
from django.db import migrations, models

import dora.services.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "services",
            "0122_rename_concernedpublic_public_alter_public_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="public",
            old_name="profile_families",
            new_name="corresponding_di_publics",
        ),
        migrations.AlterField(
            model_name="public",
            name="corresponding_di_publics",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=255,
                    validators=[dora.services.models.validate_corresponding_di_publics],
                ),
                default=list,
                size=None,
                verbose_name="Publics Data Inclusion correspondants",
            ),
        ),
    ]
