# Generated by Django 5.2.6 on 2025-09-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0123_rename_profile_families_public_corresponding_di_publics"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="concerned_public",
            new_name="publics",
        ),
        migrations.AlterField(
            model_name="service",
            name="publics",
            field=models.ManyToManyField(
                blank=True, to="services.public", verbose_name="Publics"
            ),
        ),
    ]
