# Generated by Django 5.2.6 on 2025-09-18 14:32
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE = 1755  # Être éligible aux critères IAE
ACCESS_CONDITION_SALARIE_SIAE = 1756  # Salarié d'une SIAE
ACCESS_CONDITION_INSCRIT_MISSION_LOCALE = 1757  # Inscrit à la Mission Locale
ACCESS_CONDITION_RESIDENT_QPV_OU_ZRR = 1758  # Résident QPV / ZRR
ACCESS_CONDITION_PERSONNE_NON_IMPOSABLE = 1759  # Personne non imposable

PROFILE_CHANGES: dict[int, dict[str, list[int]]] = {
    1084: {"newProfileIds": (16,)},
    1185: {
        "newProfileIds": (
            50,
            18,
        )
    },
    1070: {"newProfileIds": (26,)},
    1277: {"newProfileIds": (12,)},
    1226: {
        "newProfileIds": (
            50,
            18,
        )
    },
    925: {
        "newProfileIds": (
            51,
            26,
        )
    },
    693: {
        "newProfileIds": (
            51,
            14,
            21,
        )
    },
    690: {
        "newProfileIds": (
            51,
            14,
            26,
        )
    },
    1209: {
        "newProfileIds": (
            61,
            18,
            30,
        )
    },
    692: {"newProfileIds": (10,)},
    1216: {"newProfileIds": (18,)},
    255: {
        "newProfileIds": (
            12,
            17,
        )
    },
    852: {"newProfileIds": (26,)},
    871: {
        "newProfileIds": (
            73,
            18,
            26,
        )
    },
    1148: {},
    345: {
        "newProfileIds": (
            420,
            65,
        )
    },
    347: {
        "newProfileIds": (
            420,
            65,
        )
    },
    682: {
        "newProfileIds": (
            16,
            18,
        )
    },
    864: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    867: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    861: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    858: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    855: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    691: {"newProfileIds": (17,)},
    776: {},
    771: {},
    854: {},
    875: {"newProfileIds": (38,)},
    1083: {"newProfileIds": (38,)},
    1059: {
        "newProfileIds": (
            50,
            26,
        )
    },
    173: {},
    381: {},
    137: {},
    1261: {
        "newProfileIds": (
            50,
            56,
            45,
        )
    },
    1131: {
        "newProfileIds": (
            50,
            61,
            18,
            29,
        )
    },
    912: {},
    256: {
        "newProfileIds": (
            4,
            11,
        )
    },
    1108: {},
    1184: {"newProfileIds": (28,)},
    342: {
        "newProfileIds": (
            73,
            18,
            25,
        )
    },
    940: {
        "newProfileIds": (
            25,
            65,
        )
    },
    160: {},
    86: {},
    982: {"newProfileIds": (67,)},
    983: {"newProfileIds": (67,)},
    1080: {"newProfileIds": (67,)},
    755: {
        "newProfileIds": (
            792,
            56,
            45,
        )
    },
    366: {"newProfileIds": (6,)},
    1231: {},
    908: {},
    1100: {},
    1129: {},
    268: {
        "newProfileIds": (
            51,
            26,
        ),
        "accessConditionIds": (ACCESS_CONDITION_INSCRIT_MISSION_LOCALE,),
    },
    215: {
        "newProfileIds": (
            51,
            26,
        ),
        "accessConditionIds": (ACCESS_CONDITION_INSCRIT_MISSION_LOCALE,),
    },
    747: {
        "newProfileIds": (
            16,
            17,
        )
    },
    407: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    408: {
        "newProfileIds": (
            47,
            422,
            16,
            25,
        )
    },
    1060: {
        "newProfileIds": (
            47,
            422,
            16,
            25,
        )
    },
    1112: {
        "newProfileIds": (
            18,
            30,
        )
    },
    158: {
        "newProfileIds": (
            61,
            30,
        )
    },
    409: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    368: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    1022: {"newProfileIds": (422,)},
    1121: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    1122: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    1077: {
        "newProfileIds": (
            47,
            422,
            16,
            25,
        )
    },
    1146: {
        "newProfileIds": (
            51,
            26,
        )
    },
    1124: {
        "newProfileIds": (
            51,
            26,
        )
    },
    288: {
        "newProfileIds": (
            46,
            61,
            30,
        )
    },
    1123: {
        "newProfileIds": (
            46,
            61,
            30,
        )
    },
    1282: {"newProfileIds": (51,)},
    1285: {"newProfileIds": (51,)},
    904: {"newProfileIds": (61,)},
    1181: {
        "newProfileIds": (
            6,
            18,
        )
    },
    905: {"newProfileIds": (61,)},
    1110: {"newProfileIds": (61,)},
    1116: {
        "newProfileIds": (
            46,
            16,
        )
    },
    287: {"newProfileIds": (61,)},
    170: {"newProfileIds": (61,)},
    1042: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    1043: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    1040: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    757: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    1041: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    418: {
        "newProfileIds": (
            73,
            18,
            25,
        )
    },
    1099: {
        "newProfileIds": (
            73,
            18,
            26,
        )
    },
    688: {"newProfileIds": (61,)},
    1172: {"newProfileIds": (61,)},
    384: {
        "newProfileIds": (
            73,
            18,
        )
    },
    749: {
        "newProfileIds": (
            51,
            26,
        )
    },
    1068: {
        "newProfileIds": (
            61,
            11,
            29,
        )
    },
    988: {
        "newProfileIds": (
            16,
            18,
        ),
        "accessConditionIds": (ACCESS_CONDITION_INSCRIT_MISSION_LOCALE,),
    },
    992: {
        "newProfileIds": (
            16,
            18,
        ),
        "accessConditionIds": (ACCESS_CONDITION_INSCRIT_MISSION_LOCALE,),
    },
    1290: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    748: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    1264: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    292: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    1101: {
        "newProfileIds": (
            47,
            422,
            16,
            25,
        )
    },
    1118: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    896: {
        "newProfileIds": (
            422,
            16,
            25,
        ),
        "accessConditionIds": (ACCESS_CONDITION_INSCRIT_MISSION_LOCALE,),
    },
    1143: {
        "newProfileIds": (
            422,
            16,
            25,
        ),
        "accessConditionIds": (ACCESS_CONDITION_INSCRIT_MISSION_LOCALE,),
    },
    1119: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    995: {
        "newProfileIds": (
            422,
            16,
            25,
        ),
        "accessConditionIds": (ACCESS_CONDITION_INSCRIT_MISSION_LOCALE,),
    },
    987: {
        "newProfileIds": (
            422,
            16,
            25,
        ),
        "accessConditionIds": (ACCESS_CONDITION_INSCRIT_MISSION_LOCALE,),
    },
    902: {
        "newProfileIds": (
            68,
            16,
            29,
        )
    },
    1244: {
        "newProfileIds": (
            68,
            16,
            30,
        )
    },
    1291: {
        "newProfileIds": (
            46,
            68,
            16,
            30,
        )
    },
    1001: {
        "newProfileIds": (
            47,
            422,
            16,
            25,
        )
    },
    768: {
        "newProfileIds": (
            73,
            18,
            25,
        )
    },
    398: {
        "newProfileIds": (
            73,
            18,
            25,
        )
    },
    1081: {
        "newProfileIds": (
            73,
            18,
            25,
        )
    },
    750: {
        "newProfileIds": (
            73,
            18,
            25,
        )
    },
    880: {
        "newProfileIds": (
            47,
            73,
            18,
            25,
        )
    },
    631: {
        "newProfileIds": (
            61,
            18,
            29,
        )
    },
    1014: {
        "newProfileIds": (
            8,
            61,
            18,
            30,
        )
    },
    1013: {
        "newProfileIds": (
            61,
            18,
            30,
        )
    },
    1293: {
        "newProfileIds": (
            1611,
            29,
        )
    },
    343: {
        "newProfileIds": (
            51,
            18,
        )
    },
    1152: {
        "newProfileIds": (
            51,
            26,
        ),
        "accessConditionIds": (ACCESS_CONDITION_INSCRIT_MISSION_LOCALE,),
    },
    1468: {
        "newProfileIds": (
            51,
            26,
        ),
        "accessConditionIds": (ACCESS_CONDITION_INSCRIT_MISSION_LOCALE,),
    },
    1153: {
        "newProfileIds": (
            1611,
            61,
            30,
        )
    },
    1120: {
        "newProfileIds": (
            46,
            61,
            30,
        )
    },
    136: {"newProfileIds": (50,)},
    102: {"newProfileIds": (50,)},
    873: {"newProfileIds": (50,)},
    882: {"newProfileIds": (50,)},
    1051: {"newProfileIds": (51,)},
    1000: {
        "newProfileIds": (
            46,
            61,
            30,
        )
    },
    1232: {
        "newProfileIds": (
            61,
            30,
        ),
        "accessConditionIds": (ACCESS_CONDITION_RESIDENT_QPV_OU_ZRR,),
    },
    870: {
        "newProfileIds": (
            16,
            18,
        )
    },
    279: {"newProfileIds": (45,)},
    1171: {"newProfileIds": (74,)},
    1228: {"newProfileIds": (61,)},
    1109: {"newProfileIds": (51,)},
    984: {
        "newProfileIds": (
            46,
            61,
            29,
        )
    },
    1093: {},
    1136: {
        "newProfileIds": (
            16,
            18,
        )
    },
    1137: {
        "newProfileIds": (
            16,
            18,
        )
    },
    1138: {
        "newProfileIds": (
            16,
            18,
        )
    },
    1156: {
        "newProfileIds": (
            51,
            26,
        )
    },
    1265: {"newProfileIds": (28,)},
    897: {},
    1186: {},
    804: {},
    378: {"newProfileIds": (18,)},
    740: {},
    739: {},
    1287: {},
    1284: {},
    684: {},
    765: {},
    285: {},
    191: {},
    194: {"accessConditionIds": (ACCESS_CONDITION_PERSONNE_NON_IMPOSABLE,)},
    1281: {},
    756: {},
    979: {"newProfileIds": (38,)},
    732: {"newProfileIds": (18,)},
    733: {"newProfileIds": (18,)},
    149: {"newProfileIds": (1,)},
    98: {},
    1102: {},
    99: {"newProfileIds": (60,)},
    803: {},
    93: {},
    100: {},
    286: {},
    734: {"newProfileIds": (27,)},
    101: {
        "newProfileIds": (
            46,
            36,
            60,
        )
    },
    918: {},
    196: {},
    197: {},
    1219: {"newProfileIds": (27,)},
    1256: {},
    1078: {},
    386: {"newProfileIds": (18,)},
    175: {"newProfileIds": (18,)},
    1079: {"newProfileIds": (18,)},
    174: {"newProfileIds": (18,)},
    1220: {},
    1037: {},
    1125: {"newProfileIds": (27,)},
    1242: {},
    632: {},
    1224: {},
    92: {
        "newProfileIds": (
            46,
            36,
            60,
        )
    },
    348: {
        "newProfileIds": (
            36,
            60,
        )
    },
    79: {"newProfileIds": (6,)},
    1223: {"newProfileIds": (28,)},
    362: {"newProfileIds": (28,)},
    785: {},
    1259: {},
    1188: {},
    806: {},
    1258: {
        "newProfileIds": (
            50,
            36,
            50,
        )
    },
    677: {},
    1299: {"newProfileIds": (18,)},
    1134: {
        "newProfileIds": (
            422,
            16,
            30,
        )
    },
    1047: {
        "newProfileIds": (
            61,
            16,
            30,
        )
    },
    1044: {
        "newProfileIds": (
            61,
            16,
            30,
        )
    },
    1033: {
        "newProfileIds": (
            61,
            16,
            30,
        )
    },
    242: {},
    358: {"accessConditionIds": (ACCESS_CONDITION_SALARIE_SIAE,)},
    810: {"newProfileIds": (35,)},
    809: {"newProfileIds": (35,)},
    811: {"newProfileIds": (35,)},
    736: {"newProfileIds": (18,)},
    1114: {
        "newProfileIds": (
            51,
            26,
        )
    },
    354: {
        "newProfileIds": (
            51,
            26,
        ),
        "accessConditionIds": (ACCESS_CONDITION_INSCRIT_MISSION_LOCALE,),
    },
    1007: {
        "newProfileIds": (
            420,
            65,
        )
    },
    392: {},
    626: {"newProfileIds": (28,)},
    193: {
        "newProfileIds": (
            51,
            26,
        ),
        "accessConditionIds": (ACCESS_CONDITION_RESIDENT_QPV_OU_ZRR,),
    },
    241: {},
    1130: {},
    1141: {},
    365: {},
    187: {},
    1104: {},
    1142: {"newProfileIds": (50,)},
    999: {},
    1048: {},
    1034: {},
    1045: {},
    1049: {},
    1046: {},
    1035: {},
    1225: {
        "newProfileIds": (
            36,
            60,
        )
    },
    350: {
        "newProfileIds": (
            36,
            45,
        )
    },
    1227: {
        "newProfileIds": (
            36,
            50,
        )
    },
    627: {
        "newProfileIds": (
            36,
            60,
        )
    },
    686: {"newProfileIds": (28,)},
    1180: {},
    805: {},
    186: {"newProfileIds": (45,)},
    359: {"newProfileIds": (45,)},
    1169: {},
    138: {
        "newProfileIds": (
            36,
            45,
        )
    },
    247: {
        "newProfileIds": (
            36,
            60,
        )
    },
    246: {
        "newProfileIds": (
            36,
            60,
        )
    },
    209: {},
    257: {
        "newProfileIds": (
            47,
            422,
            16,
            25,
        ),
        "accessConditionIds": (ACCESS_CONDITION_INSCRIT_MISSION_LOCALE,),
    },
    295: {
        "newProfileIds": (
            61,
            30,
        )
    },
    996: {"newProfileIds": (3,)},
    267: {},
    1298: {"newProfileIds": (18,)},
    1243: {
        "newProfileIds": (
            50,
            16,
            65,
        )
    },
    1074: {"newProfileIds": (26,)},
    84: {},
    1189: {},
    1023: {},
    899: {},
    78: {},
    203: {"newProfileIds": (18,)},
    299: {"newProfileIds": (67,)},
    248: {
        "newProfileIds": (
            17,
            55,
        )
    },
    1237: {"newProfileIds": (16,)},
    887: {"newProfileIds": (67,)},
    766: {},
    415: {
        "newProfileIds": (
            50,
            26,
        )
    },
    1279: {
        "newProfileIds": (
            6,
            15,
        )
    },
    931: {
        "newProfileIds": (
            25,
            65,
        )
    },
    936: {
        "newProfileIds": (
            25,
            65,
        )
    },
    933: {
        "newProfileIds": (
            25,
            65,
        )
    },
    1027: {"newProfileIds": (67,)},
    744: {"newProfileIds": (46,)},
    341: {
        "newProfileIds": (
            73,
            18,
            21,
        )
    },
    930: {
        "newProfileIds": (
            73,
            18,
            25,
        )
    },
    1194: {"newProfileIds": (51,)},
    753: {"newProfileIds": (61,)},
    1270: {"newProfileIds": (18,)},
    1274: {"newProfileIds": (18,)},
    431: {"newProfileIds": (18,)},
    337: {
        "newProfileIds": (
            51,
            20,
        )
    },
    758: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    1230: {
        "newProfileIds": (
            422,
            16,
            25,
        )
    },
    1018: {
        "newProfileIds": (
            51,
            11,
            26,
        )
    },
    1204: {
        "newProfileIds": (
            73,
            18,
            25,
        )
    },
    1154: {
        "newProfileIds": (
            1611,
            61,
            30,
        )
    },
    276: {"newProfileIds": (51,)},
    1103: {
        "newProfileIds": (
            73,
            18,
        )
    },
    1075: {
        "newProfileIds": (
            73,
            18,
        )
    },
    1117: {
        "newProfileIds": (
            46,
            61,
            29,
        )
    },
    731: {
        "newProfileIds": (
            16,
            18,
        )
    },
    942: {
        "newProfileIds": (
            61,
            30,
        )
    },
    304: {},
    1173: {},
    784: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    291: {},
    266: {},
    340: {"newProfileIds": (28,)},
    1191: {},
    204: {"newProfileIds": (46,)},
    1179: {},
    274: {},
    135: {"newProfileIds": (50,)},
    1251: {},
    1253: {},
    1257: {"newProfileIds": (65,)},
    416: {"newProfileIds": (52,)},
    161: {
        "newProfileIds": (
            65,
            62,
            1615,
        )
    },
    159: {
        "newProfileIds": (
            65,
            62,
            1615,
        )
    },
    1164: {"newProfileIds": (52,)},
    414: {"newProfileIds": (52,)},
    680: {
        "newProfileIds": (
            36,
            60,
        )
    },
    681: {
        "newProfileIds": (
            36,
            60,
        )
    },
    1254: {"newProfileIds": (45,)},
    1260: {"newProfileIds": (52,)},
    1205: {},
    1170: {},
    298: {},
    166: {"newProfileIds": (65,)},
    1248: {},
    1247: {"newProfileIds": (67,)},
    1249: {},
    397: {},
    1062: {"newProfileIds": (26,)},
    165: {
        "newProfileIds": (
            61,
            30,
        )
    },
    1210: {"accessConditionIds": (ACCESS_CONDITION_ETRE_ELIGIBLE_CRITERES_IAE,)},
    754: {},
    1245: {"newProfileIds": (16,)},
}


def clean_profiles(apps, schema_editor):
    AccessCondition = apps.get_model("services", "AccessCondition")
    ConcernedPublic = apps.get_model("services", "ConcernedPublic")
    Service = apps.get_model("services", "Service")
    ServiceModel = apps.get_model("services", "ServiceModel")

    for old_profile_id, profile_changes in PROFILE_CHANGES.items():
        try:
            with schema_editor.connection.cursor() as cursor:
                cursor.execute("BEGIN")
                try:
                    logger.info("Traitement de l'ancien profil %d", old_profile_id)
                    try:
                        old_profile = ConcernedPublic.objects.get(id=old_profile_id)
                    except ConcernedPublic.DoesNotExist:
                        raise ConcernedPublic.DoesNotExist(
                            f"le profil {old_profile_id} n'existe pas"
                        )

                    services = Service.objects.filter(concerned_public=old_profile)
                    service_models = ServiceModel.objects.filter(
                        concerned_public=old_profile
                    )

                    new_profiles = None
                    access_conditions = None

                    # Récupération des nouveaux profils
                    if "newProfileIds" in profile_changes:
                        logger.info(
                            "Assignation des nouveaux profils %s",
                            profile_changes["newProfileIds"],
                        )
                        new_profiles = ConcernedPublic.objects.filter(
                            id__in=profile_changes["newProfileIds"]
                        )
                        if new_profiles.count() != len(
                            profile_changes["newProfileIds"]
                        ):
                            unfound_profile_ids = set(
                                profile_changes["newProfileIds"]
                            ) - set(new_profiles.values_list("id", flat=True))
                            raise ConcernedPublic.DoesNotExist(
                                f"un ou plusieurs publics concernés non trouvés : {unfound_profile_ids}"
                            )

                    # Récupération des conditions d'accès
                    if "accessConditionIds" in profile_changes:
                        logger.info(
                            "Assignation des conditions d'accès %s",
                            profile_changes["accessConditionIds"],
                        )
                        access_conditions = AccessCondition.objects.filter(
                            id__in=profile_changes["accessConditionIds"]
                        )
                        if access_conditions.count() != len(
                            profile_changes["accessConditionIds"]
                        ):
                            unfound_access_condition_ids = set(
                                profile_changes["accessConditionIds"]
                            ) - set(access_conditions.values_list("id", flat=True))
                            raise AccessCondition.DoesNotExist(
                                f"une ou plusieures conditions d'accès non trouvées : {unfound_access_condition_ids}"
                            )

                    # Assignation des nouveaux profils et conditions d'accès aux services
                    for service in services:
                        service.concerned_public.remove(old_profile)
                        if new_profiles:
                            service.concerned_public.add(*new_profiles)
                        if access_conditions:
                            service.access_conditions.add(*access_conditions)
                        if ACCESS_CONDITION_RESIDENT_QPV_OU_ZRR in profile_changes.get(
                            "accessConditionIds", []
                        ):
                            service.qpv_or_zrr = True
                            service.save()

                    # Assignation des nouveaux profils et conditions d'accès aux modèles de services
                    for service_model in service_models:
                        service_model.concerned_public.remove(old_profile)
                        if new_profiles:
                            service_model.concerned_public.add(*new_profiles)
                        if access_conditions:
                            service_model.access_conditions.add(*access_conditions)
                        if ACCESS_CONDITION_RESIDENT_QPV_OU_ZRR in profile_changes.get(
                            "accessConditionIds", []
                        ):
                            service_model.qpv_or_zrr = True
                            service_model.save()

                    logger.info("Suppression de l'ancien profil %d", old_profile_id)
                    old_profile.delete()

                    cursor.execute("COMMIT")
                except Exception as e:
                    cursor.execute("ROLLBACK")
                    logger.warning(
                        "Une erreur est survenue lors du traitement du profil %d : %s",
                        old_profile_id,
                        str(e),
                    )
                    continue
        except Exception as e:
            logger.error(
                "Erreur de transaction pour le profil %d : %s",
                old_profile_id,
                str(e),
            )
            continue


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0124_rename_concerned_public_service_publics"),
    ]

    operations = [
        migrations.RunPython(clean_profiles, reverse_code=migrations.RunPython.noop),
    ]
