# Generated by Django 5.2.7 on 2025-11-19 15:39

from django.db import migrations

PERSONNES_EN_SITUATION_DE_HANDICAP_PUBLIC_ID = 46


def assign_public_handicap(apps, schema_editor):
    Public = apps.get_model("services", "Public")
    Service = apps.get_model("services", "Service")

    try:
        handicap_public = Public.objects.get(
            id=PERSONNES_EN_SITUATION_DE_HANDICAP_PUBLIC_ID
        )
    except Public.DoesNotExist:
        # N'existe pas dans la base de données de test -> ne rien faire
        return

    for service in Service.objects.filter(
        subcategories__value__startswith="handicap--"
    ):
        service.publics.add(handicap_public)


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0126_clean_profiles_part_2"),
    ]

    operations = [
        migrations.RunPython(
            assign_public_handicap, reverse_code=migrations.RunPython.noop
        ),
    ]
