# Generated by Django 5.2.7 on 2025-11-10 14:39

from data_inclusion.schema.v1 import Thematique
from django.db import migrations

CATEGORY_LABELS = {
    "lecture-ecriture-calcul": "Lecture, écriture, calcul",
    "difficultes-financieres": "Difficultés financières",
    "difficultes-administratives-ou-juridiques": "Difficultés administratives ou juridiques",
    "creer-une-entreprise": "Créer une entreprise",
}


def add_thematiques_di_v1(apps, schema_editor):
    ServiceCategory = apps.get_model("services", "ServiceCategory")
    ServiceSubCategory = apps.get_model("services", "ServiceSubCategory")
    for thematique in Thematique:
        category, _ = thematique.value.split("--")
        try:
            ServiceCategory.objects.get(value=category)
        except ServiceCategory.DoesNotExist:
            ServiceCategory.objects.create(
                value=category, label=CATEGORY_LABELS[category]
            )
        try:
            subcategory = ServiceSubCategory.objects.get(value=thematique)
            subcategory.label = thematique.label
            subcategory.save()
        except ServiceSubCategory.DoesNotExist:
            ServiceSubCategory.objects.create(value=thematique, label=thematique.label)


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0126_clean_profiles_part_2"),
    ]

    operations = [
        migrations.RunPython(
            add_thematiques_di_v1, reverse_code=migrations.RunPython.noop
        ),
    ]
