# Generated by Django 5.2.8 on 2025-12-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0127_assignation_public_handicap"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="is_obsolete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicesubcategory",
            name="is_obsolete",
            field=models.BooleanField(default=False),
        ),
    ]
