# Generated by Django 5.2.7 on 2025-11-10 14:39

import logging

from data_inclusion.schema.v1 import Thematique
from django.db import migrations

logger = logging.getLogger(__name__)

MAPPING_THEMATIQUES = {
    "acces-aux-droits-et-citoyennete--accompagnement-dans-les-demarches-administratives": [
        "difficultes-administratives-ou-juridiques--accompagnement-aux-demarches-administratives"
    ],
    "acces-aux-droits-et-citoyennete--accompagnement-juridique": [
        "difficultes-administratives-ou-juridiques--prendre-en-compte-une-problematique-judiciaire"
    ],
    "acces-aux-droits-et-citoyennete--connaitre-ses-droits": [
        "difficultes-administratives-ou-juridiques--accompagnement-pour-lacces-aux-droits"
    ],
    "acces-aux-droits-et-citoyennete--demandeurs-dasile-et-naturalisation": [
        "difficultes-administratives-ou-juridiques--accompagnement-pour-lacces-a-la-citoyennete"
    ],
    "acces-aux-droits-et-citoyennete--developpement-durable": [
        "remobilisation--benevolat-action-citoyenne"
    ],
    "acces-aux-droits-et-citoyennete--faciliter-laction-citoyenne": [
        "remobilisation--benevolat-action-citoyenne"
    ],
    "accompagnement-social-et-professionnel-personnalise--decrochage-scolaire": [
        "famille--soutien-a-la-parentalite-et-a-leducation"
    ],
    "accompagnement-social-et-professionnel-personnalise--definition-du-projet-professionnel": [
        "choisir-un-metier--confirmer-son-choix-de-metier"
    ],
    "apprendre-francais--accompagnement-insertion-pro": [
        "lecture-ecriture-calcul--maitriser-le-francais"
    ],
    "apprendre-francais--communiquer-vie-tous-les-jours": [
        "lecture-ecriture-calcul--maitriser-le-francais"
    ],
    "apprendre-francais--suivre-formation": [
        "lecture-ecriture-calcul--maitriser-le-francais"
    ],
    "choisir-un-metier--confirmer-son-choix-de-metier": [
        "choisir-un-metier--confirmer-son-choix-de-metier"
    ],
    "choisir-un-metier--connaitre-les-opportunites-demploi": [
        "choisir-un-metier--connaitre-les-opportunites-demploi"
    ],
    "choisir-un-metier--decouvrir-un-metier-ou-un-secteur-dactivite": [
        "choisir-un-metier--decouvrir-un-metier-ou-un-secteur-dactivite"
    ],
    "choisir-un-metier--identifier-ses-points-forts-et-ses-competences": [
        "choisir-un-metier--identifier-ses-points-forts-et-ses-competences"
    ],
    "creation-activite--definir-son-projet-de-creation-dentreprise": [
        "creer-une-entreprise--definir-son-projet-de-creation-dentreprise"
    ],
    "creation-activite--developper-son-entreprise": [
        "creer-une-entreprise--developper-son-entreprise"
    ],
    "creation-activite--financer-son-projet": [
        "creer-une-entreprise--structurer-son-projet-de-creation-dentreprise"
    ],
    "creation-activite--reseautage-pour-createurs-dentreprise": [
        "creer-une-entreprise--developper-son-entreprise"
    ],
    "creation-activite--structurer-son-projet-de-creation-dentreprise": [
        "creer-une-entreprise--structurer-son-projet-de-creation-dentreprise"
    ],
    "equipement-et-alimentation--acces-a-du-materiel-informatique": [
        "numerique--acquerir-un-equipement"
    ],
    "equipement-et-alimentation--acces-a-un-telephone-et-un-abonnement": [
        "numerique--acquerir-un-equipement"
    ],
    "equipement-et-alimentation--alimentation": [
        "equipement-et-alimentation--alimentation"
    ],
    "equipement-et-alimentation--electromenager": [
        "equipement-et-alimentation--electromenager"
    ],
    "equipement-et-alimentation--habillement": [
        "equipement-et-alimentation--habillement"
    ],
    "famille--accompagnement-femme-enceinte-bebe-jeune-enfant": [
        "famille--soutien-a-la-parentalite-et-a-leducation"
    ],
    "famille--garde-denfants": ["famille--garde-denfants"],
    "famille--information-et-accompagnement-des-parents": [
        "famille--soutien-a-la-parentalite-et-a-leducation"
    ],
    "famille--jeunes-sans-soutien-familial": ["remobilisation--lien-social"],
    "famille--soutien-a-la-parentalite": [
        "famille--soutien-a-la-parentalite-et-a-leducation"
    ],
    "famille--soutien-aux-familles": ["famille--soutien-aidants"],
    "famille--violences-intrafamiliales": [
        "famille--surmonter-conflits-separation-violence"
    ],
    "gestion-financiere--acces-au-micro-credit": [
        "difficultes-financieres--acquerir-une-autonomie-budgetaire"
    ],
    "gestion-financiere--accompagnement-aux-personnes-en-difficultes-financieres": [
        "difficultes-financieres--acquerir-une-autonomie-budgetaire"
    ],
    "gestion-financiere--apprendre-a-gerer-son-budget": [
        "difficultes-financieres--ameliorer-sa-gestion-budgetaire"
    ],
    "gestion-financiere--beneficier-daides-financieres": [
        "difficultes-financieres--acquerir-une-autonomie-budgetaire"
    ],
    "gestion-financiere--creation-et-utilisation-dun-compte-bancaire": [
        "difficultes-financieres--acquerir-une-autonomie-budgetaire"
    ],
    "gestion-financiere--obtenir-une-aide-alimentaire": [
        "equipement-et-alimentation--alimentation"
    ],
    "gestion-financiere--prevention-et-gestion-du-surendettement": [
        "difficultes-financieres--situation-dendettement-surendettement"
    ],
    "handicap--accompagnement-par-une-structure-specialisee": [
        "difficultes-administratives-ou-juridiques--accompagnement-pour-lacces-aux-droits",
        "trouver-un-emploi--maintien-dans-lemploi",
    ],
    "handicap--adaptation-au-poste-de-travail": [
        "trouver-un-emploi--maintien-dans-lemploi"
    ],
    "handicap--adapter-son-logement": [
        "logement-hebergement--se-maintenir-dans-le-logement"
    ],
    "handicap--connaissance-des-droits-des-travailleurs": [
        "difficultes-administratives-ou-juridiques--accompagnement-pour-lacces-aux-droits"
    ],
    "handicap--faire-reconnaitre-un-handicap": [
        "sante--constituer-un-dossier-mdph-invalidite"
    ],
    "handicap--favoriser-le-retour-et-le-maintien-dans-lemploi": [
        "trouver-un-emploi--maintien-dans-lemploi"
    ],
    "handicap--mobilite-des-personnes-en-situation-de-handicap": [
        "mobilite--etre-accompagne-dans-son-parcours-mobilite"
    ],
    "illettrisme--accompagner-scolarite": [
        "famille--soutien-a-la-parentalite-et-a-leducation"
    ],
    "illettrisme--ameliorer-vocabulaire": [
        "lecture-ecriture-calcul--maitriser-le-francais"
    ],
    "illettrisme--etre-autonome": [
        "lecture-ecriture-calcul--maitriser-le-francais",
        "lecture-ecriture-calcul--maitriser-le-calcul",
    ],
    "illettrisme--info-acquisition-connaissances": [
        "lecture-ecriture-calcul--maitriser-le-francais",
        "lecture-ecriture-calcul--maitriser-le-calcul",
    ],
    "illettrisme--permis-conduire": ["mobilite--preparer-un-permis"],
    "illettrisme--reperer-situation-illettrisme": [
        "lecture-ecriture-calcul--maitriser-le-francais",
        "lecture-ecriture-calcul--maitriser-le-calcul",
    ],
    "illettrisme--surmonter-trouble-apprentissage": [
        "lecture-ecriture-calcul--maitriser-le-francais",
        "lecture-ecriture-calcul--maitriser-le-calcul",
    ],
    "illettrisme--trouver-emploi-formation": ["se-former--trouver-sa-formation"],
    "illettrisme--utiliser-numerique": [
        "numerique--maitriser-les-fondamentaux-du-numerique"
    ],
    "illettrisme--valider-certification-clea": [
        "preparer-sa-candidature--valoriser-ses-competences"
    ],
    "logement-hebergement--besoin-dadapter-mon-logement": [
        "logement-hebergement--sinformer-sur-les-demarches-liees-a-lacces-au-logement"
    ],
    "logement-hebergement--connaissance-de-ses-droits-et-interlocuteurs": [
        "logement-hebergement--sinformer-sur-les-demarches-liees-a-lacces-au-logement"
    ],
    "logement-hebergement--demenagement": ["logement-hebergement--changer-de-logement"],
    "logement-hebergement--etre-accompagne-pour-se-loger": [
        "logement-hebergement--sinformer-sur-les-demarches-liees-a-lacces-au-logement"
    ],
    "logement-hebergement--gerer-son-budget": [
        "logement-hebergement--reduire-les-impayes-de-loyer"
    ],
    "logement-hebergement--mal-loges-sans-logis": [
        "logement-hebergement--rechercher-une-solution-dhebergement-temporaire",
        "logement-hebergement--changer-de-logement",
    ],
    "logement-hebergement--probleme-avec-son-logement": [
        "logement-hebergement--changer-de-logement"
    ],
    "logement-hebergement--reprendre-un-emploi-ou-une-formation": [
        "trouver-un-emploi--repondre-a-des-offres-demploi"
    ],
    "mobilite--acheter-un-vehicule-motorise": ["mobilite--acceder-a-un-vehicule"],
    "mobilite--acheter-un-velo": ["mobilite--acceder-a-un-vehicule"],
    "mobilite--aides-a-la-reprise-demploi-ou-a-la-formation": [
        "mobilite--financer-ma-mobilite"
    ],
    "mobilite--apprendre-a-utiliser-un-deux-roues": ["mobilite--preparer-un-permis"],
    "mobilite--comprendre-et-utiliser-les-transports-en-commun": [
        "mobilite--mobilite-douce-partagee-collective"
    ],
    "mobilite--entretenir-reparer-son-vehicule": [
        "mobilite--entretenir-reparer-son-vehicule"
    ],
    "mobilite--etre-accompagne-dans-son-parcours-mobilite": [
        "mobilite--etre-accompagne-dans-son-parcours-mobilite"
    ],
    "mobilite--financer-mon-projet-mobilite": ["mobilite--financer-ma-mobilite"],
    "mobilite--louer-un-vehicule": ["mobilite--acceder-a-un-vehicule"],
    "mobilite--preparer-son-permis-de-conduire-se-reentrainer-a-la-conduite": [
        "mobilite--preparer-un-permis"
    ],
    "numerique--acceder-a-du-materiel": ["numerique--acquerir-un-equipement"],
    "numerique--acceder-a-une-connexion-internet": [
        "numerique--acceder-a-une-connexion-internet"
    ],
    "numerique--accompagner-les-demarches-de-sante": ["sante--acces-aux-soins"],
    "numerique--approfondir-ma-culture-numerique": [
        "numerique--maitriser-les-fondamentaux-du-numerique"
    ],
    "numerique--creer-avec-le-numerique": [
        "creer-une-entreprise--definir-son-projet-de-creation-dentreprise"
    ],
    "numerique--creer-et-developper-mon-entreprise": [
        "creer-une-entreprise--developper-son-entreprise"
    ],
    "numerique--devenir-autonome-dans-les-demarches-administratives": [
        "difficultes-administratives-ou-juridiques--accompagnement-aux-demarches-administratives"
    ],
    "numerique--favoriser-mon-insertion-professionnelle": [
        "preparer-sa-candidature--organiser-ses-demarches-de-recherche-demploi"
    ],
    "numerique--prendre-en-main-un-ordinateur": [
        "numerique--maitriser-les-fondamentaux-du-numerique"
    ],
    "numerique--prendre-en-main-un-smartphone-ou-une-tablette": [
        "numerique--maitriser-les-fondamentaux-du-numerique"
    ],
    "numerique--promouvoir-la-citoyennete-numerique": [
        "numerique--maitriser-les-fondamentaux-du-numerique"
    ],
    "numerique--realiser-des-demarches-administratives-avec-un-accompagnement": [
        "numerique--acceder-a-des-services-en-ligne"
    ],
    "numerique--s-equiper-en-materiel-informatique": [
        "numerique--acquerir-un-equipement"
    ],
    "numerique--soutenir-la-parentalite-et-l-education-avec-le-numerique": [
        "famille--soutien-a-la-parentalite-et-a-leducation"
    ],
    "numerique--utiliser-le-numerique-au-quotidien": [
        "numerique--maitriser-les-fondamentaux-du-numerique"
    ],
    "preparer-sa-candidature--developper-son-reseau": [
        "preparer-sa-candidature--developper-son-reseau"
    ],
    "preparer-sa-candidature--organiser-ses-demarches-de-recherche-demploi": [
        "preparer-sa-candidature--organiser-ses-demarches-de-recherche-demploi"
    ],
    "preparer-sa-candidature--realiser-un-cv-et-ou-une-lettre-de-motivation": [
        "preparer-sa-candidature--realiser-un-cv-et-ou-une-lettre-de-motivation"
    ],
    "preparer-sa-candidature--valoriser-ses-competences": [
        "preparer-sa-candidature--valoriser-ses-competences"
    ],
    "remobilisation--bien-etre": ["remobilisation--bien-etre-confiance-en-soi"],
    "remobilisation--decouvrir-son-potentiel-via-le-sport-et-la-culture": [
        "remobilisation--activites-sportives-et-culturelles"
    ],
    "remobilisation--discrimination": ["remobilisation--bien-etre-confiance-en-soi"],
    "remobilisation--identifier-ses-competences-et-aptitudes": [
        "choisir-un-metier--identifier-ses-points-forts-et-ses-competences"
    ],
    "remobilisation--lien-social": ["remobilisation--lien-social"],
    "remobilisation--participer-a-des-actions-solidaires-ou-de-benevolat": [
        "remobilisation--benevolat-action-citoyenne"
    ],
    "remobilisation--pression-sociale": ["remobilisation--lien-social"],
    "remobilisation--restaurer-sa-confiance-son-image-de-soi": [
        "remobilisation--bien-etre-confiance-en-soi"
    ],
    "sante--accompagnement-de-la-femme-enceinte-du-bebe-et-du-jeune-enfant": [
        "famille--soutien-a-la-parentalite-et-a-leducation"
    ],
    "sante--accompagner-les-traumatismes": ["sante--sante-mentale"],
    "sante--bien-etre-psychologique": ["sante--sante-mentale"],
    "sante--diagnostic-et-accompagnement-a-lemployabilite": ["sante--acces-aux-soins"],
    "sante--faire-face-a-une-situation-daddiction": ["sante--addictions"],
    "sante--obtenir-la-prise-en-charge-de-frais-medicaux": ["sante--acces-aux-soins"],
    "sante--prevention-et-acces-aux-soins": ["sante--acces-aux-soins"],
    "sante--se-soigner-et-prevenir-la-maladie": ["sante--acces-aux-soins"],
    "sante--vie-relationnelle-et-affective": ["sante--sante-sexuelle"],
    "se-former--monter-son-dossier-de-formation": [
        "se-former--monter-son-dossier-de-formation"
    ],
    "se-former--trouver-sa-formation": ["se-former--trouver-sa-formation"],
    "se-former--utiliser-le-numerique": [
        "numerique--maitriser-les-fondamentaux-du-numerique"
    ],
    "souvrir-a-linternational--connaitre-les-opportunites-demploi-a-letranger": [
        "souvrir-a-linternational--sorganiser-suite-a-son-retour-en-france"
    ],
    "souvrir-a-linternational--sinformer-sur-les-aides-pour-travailler-a-letranger": [
        "souvrir-a-linternational--sinformer-sur-les-aides-pour-travailler-a-letranger"
    ],
    "souvrir-a-linternational--sorganiser-suite-a-son-retour-en-france": [
        "souvrir-a-linternational--sorganiser-suite-a-son-retour-en-france"
    ],
    "trouver-un-emploi--convaincre-un-recruteur-en-entretien": [
        "trouver-un-emploi--convaincre-un-recruteur-en-entretien"
    ],
    "trouver-un-emploi--faire-des-candidatures-spontanees": [
        "trouver-un-emploi--faire-des-candidatures-spontanees"
    ],
    "trouver-un-emploi--repondre-a-des-offres-demploi": [
        "trouver-un-emploi--repondre-a-des-offres-demploi"
    ],
    "trouver-un-emploi--suivre-ses-candidatures-et-relancer-les-employeurs": [
        "trouver-un-emploi--suivre-ses-candidatures-et-relancer-les-employeurs"
    ],
}


def check_thematiques_exist_in_dora(apps, schema_editor):
    ServiceCategory = apps.get_model("services", "ServiceCategory")
    ServiceSubCategory = apps.get_model("services", "ServiceSubCategory")
    category_values = set()
    subcategory_values = set()

    # Collecte de toutes les catégories et sous-catégories utilisées dans les thématiques (anciennes et nouvelles)
    for old_thematique, new_thematiques in MAPPING_THEMATIQUES.items():
        thematiques = [old_thematique] + new_thematiques
        for thematique in thematiques:
            category_value, _ = thematique.split("--")
            category_values.add(category_value)
        subcategory_values.add(thematique)

    # Vérification de l'existence des catégories et sous-catégories
    invalid_categories = [
        v
        for v in category_values
        if not ServiceCategory.objects.filter(value=v).exists()
    ]
    invalid_subcategories = [
        v
        for v in subcategory_values
        if not ServiceSubCategory.objects.filter(value=v).exists()
    ]

    # Si des catégories ou sous-catégories sont invalides, on interrompt la migration
    if invalid_categories or invalid_subcategories:
        raise Exception(
            "[check_thematiques_exist_in_dora] "
            f"Invalid categories: {', '.join(invalid_categories)}. "
            f"Invalid subcategories: {', '.join(invalid_subcategories)}."
        )


def check_thematiques_exist_in_di_v1(apps, schema_editor):
    # Vérification de l'existence des nouvelles thématiques dans le référentiel DI v1
    for thematiques in MAPPING_THEMATIQUES.values():
        invalid_thematiques = {
            thematique for thematique in thematiques if thematique not in Thematique
        }

    # Si des thématiques sont invalides, on interrompt la migration
    if invalid_thematiques:
        raise Exception(
            "[check_thematiques_exist_in_di_v1] "
            f"Invalid DI v1 thematiques: {', '.join(invalid_thematiques)}."
        )


def assign_new_thematiques(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    ServiceCategory = apps.get_model("services", "ServiceCategory")
    ServiceSubCategory = apps.get_model("services", "ServiceSubCategory")

    for old_thematique, new_thematiques in MAPPING_THEMATIQUES.items():
        if len(new_thematiques) == 1 and new_thematiques[0] == old_thematique:
            # Si la thématique est la même, on passe à la suivante
            continue

        # Récupération de la catégorie et de la sous-catégorie correspondant à l'ancienne thématique
        try:
            old_category = ServiceCategory.objects.get(
                value=old_thematique.split("--")[0]
            )
            old_subcategory = ServiceSubCategory.objects.get(value=old_thematique)
        except ServiceCategory.DoesNotExist:
            continue
        except ServiceSubCategory.DoesNotExist:
            continue

        # Récupération des catégories et sous-catégories correspondant aux nouvelles thématiques
        new_categories = []
        new_subcategories = []
        for thematique_output in new_thematiques:
            if thematique_output == old_thematique:
                continue
            new_categories.append(
                ServiceCategory.objects.get(value=thematique_output.split("--")[0])
            )
            new_subcategories.append(
                ServiceSubCategory.objects.get(value=thematique_output)
            )

        # Mise à jour des services et modèles de services
        # _base_manager pour avoir les services et les modèles de services
        for service in Service._base_manager.filter(categories=old_category):
            service.categories.remove(old_category)
            service.categories.add(*new_categories)
        for service in Service._base_manager.filter(subcategories=old_subcategory):
            service.subcategories.remove(old_subcategory)
            service.subcategories.add(*new_subcategories)


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0128_add_thematiques_di_v1"),
    ]

    operations = [
        migrations.RunPython(
            check_thematiques_exist_in_dora, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            check_thematiques_exist_in_di_v1, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            assign_new_thematiques, reverse_code=migrations.RunPython.noop
        ),
    ]
