# Generated by Django 5.2.8 on 2025-12-09 12:54

from django.db import migrations


def mark_all_categories_and_subcategories_obsolete(apps, schema_editor):
    ServiceCategory = apps.get_model("services", "ServiceCategory")
    ServiceSubCategory = apps.get_model("services", "ServiceSubCategory")

    ServiceCategory.objects.all().update(is_obsolete=True)
    ServiceSubCategory.objects.all().update(is_obsolete=True)


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0128_servicecategory_servicesubcategory_is_obsolete"),
    ]

    operations = [
        migrations.RunPython(
            mark_all_categories_and_subcategories_obsolete,
            migrations.RunPython.noop,
        ),
    ]
