# Generated by Django 5.2.7 on 2025-11-10 14:39

from data_inclusion.schema.v1 import Thematique
from django.db import migrations

CATEGORY_LABELS = {
    "choisir-un-metier": "Choisir un métier",
    "creer-une-entreprise": "Créer une entreprise",
    "difficultes-administratives-ou-juridiques": "Difficultés administratives ou juridiques",
    "difficultes-financieres": "Difficultés financières",
    "equipement-et-alimentation": "Équipement et alimentation",
    "famille": "Famille",
    "lecture-ecriture-calcul": "Lecture, écriture et calcul",
    "logement-hebergement": "Logement et hébergement",
    "mobilite": "Mobilité",
    "numerique": "Numérique",
    "preparer-sa-candidature": "Préparer sa candidature",
    "remobilisation": "Remobilisation",
    "sante": "Santé",
    "se-former": "Se former",
    "souvrir-a-linternational": "S’ouvrir à l’international",
    "trouver-un-emploi": "Trouver un emploi",
}


def add_thematiques_di_v1(apps, schema_editor):
    ServiceCategory = apps.get_model("services", "ServiceCategory")
    ServiceSubCategory = apps.get_model("services", "ServiceSubCategory")
    for thematique in Thematique:
        category_value, _ = thematique.value.split("--")
        try:
            category = ServiceCategory.objects.get(value=category_value)
            category.label = CATEGORY_LABELS[category_value]
            category.save()
        except ServiceCategory.DoesNotExist:
            ServiceCategory.objects.create(
                value=category_value, label=CATEGORY_LABELS[category_value]
            )
        try:
            subcategory = ServiceSubCategory.objects.get(value=thematique)
            subcategory.label = thematique.label
            subcategory.save()
        except ServiceSubCategory.DoesNotExist:
            ServiceSubCategory.objects.create(value=thematique, label=thematique.label)


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0129_mark_category_subcategory_obsolete"),
    ]

    operations = [
        migrations.RunPython(
            add_thematiques_di_v1, reverse_code=migrations.RunPython.noop
        ),
    ]
