# Generated by Django 5.2.7 on 2025-11-19 10:12

import logging

from data_inclusion.schema.v1 import Thematique
from django.db import migrations

logger = logging.getLogger(__name__)


def delete_old_thematiques(apps, schema_editor):
    ServiceCategory = apps.get_model("services", "ServiceCategory")
    ServiceSubCategory = apps.get_model("services", "ServiceSubCategory")

    ServiceSubCategory.objects.exclude(value__in=Thematique).delete()

    ServiceCategory.objects.exclude(
        value__in=set(Thematique.value.split("--")[0] for Thematique in Thematique)
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0130_assignation_thematiques_di_v1"),
    ]

    operations = [
        migrations.RunPython(
            delete_old_thematiques, reverse_code=migrations.RunPython.noop
        ),
    ]
