# Generated by Django 5.2.7 on 2025-11-17 15:34

import csv
import logging
from pathlib import Path

from django.db import migrations

logger = logging.getLogger(__name__)

DATA_FILENAME = "assignation-thematiques.csv"


def load_assignations():
    data_path = Path(__file__).resolve().parent / "data" / DATA_FILENAME
    if not data_path.exists():
        raise FileNotFoundError(
            f"Missing thematique assignment file at {data_path.as_posix()}"
        )

    assignations = {}
    with data_path.open() as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            service_id = row["service_id"].strip()
            raw_values = (row.get("thematiques") or "").strip()
            if not service_id or not raw_values:
                continue
            thematiques = [
                value.strip() for value in raw_values.splitlines() if value.strip()
            ]
            if not thematiques:
                continue
            assignations[service_id] = thematiques

    return assignations


def assign_thematiques(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    ServiceCategory = apps.get_model("services", "ServiceCategory")
    ServiceSubCategory = apps.get_model("services", "ServiceSubCategory")

    assignations = load_assignations()
    if not assignations:
        logger.info("[assign_thematiques] No assignations loaded, skipping.")
        return

    needed_subcategory_values = {
        thematique for values in assignations.values() for thematique in values
    }
    needed_category_values = {
        thematique.split("--")[0] for thematique in needed_subcategory_values
    }

    subcategories = {
        subcategory.value: subcategory
        for subcategory in ServiceSubCategory.objects.filter(
            value__in=needed_subcategory_values
        )
    }
    categories = {
        category.value: category
        for category in ServiceCategory.objects.filter(value__in=needed_category_values)
    }

    missing_subcategories = needed_subcategory_values - subcategories.keys()
    missing_categories = needed_category_values - categories.keys()
    if missing_subcategories or missing_categories:
        raise ValueError(
            "[assign_thematiques] Missing categories/subcategories: "
            f"{', '.join(sorted(missing_categories)) or 'none'} / "
            f"{', '.join(sorted(missing_subcategories)) or 'none'}"
        )

    service_ids = set(assignations.keys())
    services_qs = Service.objects.filter(id__in=service_ids)
    found_service_ids = {
        str(service_id) for service_id in services_qs.values_list("id", flat=True)
    }
    missing_services = service_ids - found_service_ids
    if missing_services:
        logger.warning(
            "[assign_thematiques] Skipping %s unknown services (e.g. %s)",
            len(missing_services),
            next(iter(missing_services)),
        )

    for service in services_qs.iterator():
        service_id = str(service.id)
        thematiques = assignations.get(service_id)
        if not thematiques:
            continue
        new_subcategories = [subcategories[value] for value in thematiques]
        new_categories = {categories[value.split("--")[0]] for value in thematiques}
        service.categories.set(new_categories)
        service.subcategories.set(new_subcategories)


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0131_conversion_thematiques_di_v1"),
    ]

    operations = [
        migrations.RunPython(
            assign_thematiques, reverse_code=migrations.RunPython.noop
        ),
    ]
