# Generated by Django 5.2.9 on 2026-01-14 15:46

from django.db import migrations


def strip_obsolete_categories_from_services(apps, schema_editor):
    """Supprime les catégories et sous-catégories obsolètes des services."""
    Service = apps.get_model("services", "Service")
    ServiceCategory = apps.get_model("services", "ServiceCategory")
    ServiceSubCategory = apps.get_model("services", "ServiceSubCategory")

    # Utilisation du manager de base pour contourner ExcludeObsoleteManager
    obsolete_categories = ServiceCategory._base_manager.filter(is_obsolete=True)
    obsolete_subcategories = ServiceSubCategory._base_manager.filter(is_obsolete=True)

    # Suppression des catégories obsolètes des services
    for category in obsolete_categories:
        services = Service.objects.filter(categories=category)
        for service in services:
            service.categories.remove(category)

    # Suppression des sous-catégories obsolètes des services
    for subcategory in obsolete_subcategories:
        services = Service.objects.filter(subcategories=subcategory)
        for service in services:
            service.subcategories.remove(subcategory)


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0132_assignation_thematiques_di_v1"),
    ]

    operations = [
        migrations.RunPython(
            strip_obsolete_categories_from_services,
            migrations.RunPython.noop,
        ),
    ]
