# Generated by Django 6.0.1 on 2026-01-13 15:27

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def migrate_fee_conditions(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    ServiceFee = apps.get_model("services", "ServiceFee")

    gratuit_sous_condition = ServiceFee.objects.filter(
        value="gratuit-sous-conditions"
    ).first()
    adhesion = ServiceFee.objects.filter(value="adhesion").first()
    gratuit = ServiceFee.objects.filter(value="gratuit").first()
    payant = ServiceFee.objects.filter(value="payant").first()

    if gratuit_sous_condition and gratuit:
        services_to_update = Service.objects.filter(
            fee_condition=gratuit_sous_condition
        )
        count = services_to_update.update(fee_condition=gratuit)
        if count > 0:
            logger.info(
                "[migrate_fee_conditions] Migré %s service(s) de 'gratuit-sous-conditions' vers 'gratuit'",
                count,
            )
        gratuit_sous_condition.delete()
        logger.info("[migrate_fee_conditions] Supprimé 'gratuit-sous-conditions'")

    if adhesion and payant:
        services_to_update = Service.objects.filter(fee_condition=adhesion)
        count = services_to_update.update(fee_condition=payant)
        if count > 0:
            logger.info(
                "[migrate_fee_conditions] Migré %s service(s) de 'adhesion' vers 'payant'",
                count,
            )
        adhesion.delete()
        logger.info("[migrate_fee_conditions] Supprimé 'adhesion'")


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0133_strip_obsolete_subcategories_from_services"),
    ]

    operations = [
        migrations.RunPython(
            migrate_fee_conditions, reverse_code=migrations.RunPython.noop
        ),
    ]
