# Generated by Django 6.0.1 on 2026-01-13 15:53

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def migrate_service_kinds(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    ServiceKind = apps.get_model("services", "ServiceKind")

    mappings = [
        ("financement", "aide-financiere"),
        ("autonomie", "aide-materielle"),
        ("numerique", "atelier"),
        ("accueil", "information"),
    ]

    for source_value, dest_value in mappings:
        source_kind = ServiceKind.objects.filter(value=source_value).first()
        dest_kind = ServiceKind.objects.filter(value=dest_value).first()

        if not source_kind:
            logger.info(
                "[migrate_service_kinds] Type de service source '%s' non trouvé, ignoré",
                source_value,
            )
            continue

        if not dest_kind:
            logger.warning(
                "[migrate_service_kinds] Type de service destination '%s' non trouvé, ignoré",
                dest_value,
            )
            continue

        services_to_update = Service.objects.filter(kinds=source_kind).distinct()
        count = 0

        for service in services_to_update:
            if dest_kind not in service.kinds.all():
                service.kinds.add(dest_kind)
            service.kinds.remove(source_kind)
            count += 1

        if count > 0:
            logger.info(
                "[migrate_service_kinds] Migré %s service(s) de '%s' vers '%s'",
                count,
                source_value,
                dest_value,
            )

        source_kind.delete()
        logger.info(
            "[migrate_service_kinds] Supprimé '%s'",
            source_value,
        )


def migrate_delegation_kind(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    ServiceKind = apps.get_model("services", "ServiceKind")

    delegation_kind = ServiceKind.objects.filter(value="delegation").first()
    if not delegation_kind:
        logger.info(
            "[migrate_delegation_kind] Type de service 'delegation' non trouvé, ignoré"
        )
        return

    slug_to_kind_mapping = {
        "mission-locale-est-ecoute-psychologique": "accompagnement",
        "fol-de-savoie-mediation-numerique-cffd": "atelier",
        "wakimedia-mediation-numerique": "atelier",
        "universite-populaire-hpsy-coordination-creches": "aide-materielle",
        "ariane-formation-mediation-numerique-cgri": "atelier",
        "parcoude-association-recrutement-ouvrier-": "accompagnement",
        "ergos-32-633-occuper-un-emploi-ukyn": "accompagnement",
        "lattelle-numerique-mediation-numerique": "accompagnement",
        "cc-de-la-haute-somme-mediation-numerique-mnxv": "accompagnement",
        "centre-social-interc-yvcv-mediation-numerique-zief": "accompagnement",
        "adworks-12-adworks-t-nzkh-missions-dinterim-da": "accompagnement",
        "agence-pole-emploi-s-jpwy-mediation-numerique": "aide-materielle",
        "agence-pole-emploi-s-jpwy-mediation-numerique-mxcn": "aide-materielle",
        "solideco-mediation-numerique-qdpt": "accompagnement",
        "passeurs-de-mots-ecrivain-public-soci": "accompagnement",
        "urbilog-renfort-ponctuel-et-": "accompagnement",
        "ccas-ctre-com-action-laxb-mediation-numerique": "accompagnement",
        "formavente-referent-rsa": "accompagnement",
        "association-la-canop-mediation-numerique-izlz": "accompagnement",
        "janus-creil-inter-ac-suite-des-parcours": "accompagnement",
        "ergos-79-642-agent-de-conditionne": "accompagnement",
        "ergos-79-642-manuvre-batiment": "accompagnement",
        "ergos-79-642-operateur-polyvalent": "accompagnement",
        "ergos-79-642-ouvrier-vrd-travaux-": "accompagnement",
        "ergos-79-642-agent-dentretien-des": "accompagnement",
        "ergos-79-642-coffreur-prefabrique": "accompagnement",
        "ergos-79-642-ouvrier-dabattoir": "accompagnement",
        "ergos-79-642-preparateur-de-comma": "accompagnement",
        "ergos-79-642-conducteur-de-ligne-": "accompagnement",
        "prestim-trouver-en-emploi": "accompagnement",
        "isa-interim-ofkf-isa-interim": "accompagnement",
        "communaute-de-commun-lmix-clause-sociale-emplo": "accompagnement",
    }

    count_migrated = 0
    count_not_found = 0
    count_no_delegation = 0

    for slug, new_kind_value in slug_to_kind_mapping.items():
        service = Service.objects.filter(slug=slug).first()

        if not service:
            logger.warning(
                "[migrate_delegation_services_manually] Service avec slug '%s' non trouvé",
                slug,
            )
            count_not_found += 1
            continue

        if delegation_kind not in service.kinds.all():
            logger.warning(
                "[migrate_delegation_services_manually] Service '%s' n'a pas le kind 'delegation', ignoré",
                slug,
            )
            count_no_delegation += 1
            continue

        new_kind = ServiceKind.objects.filter(value=new_kind_value).first()
        if not new_kind:
            logger.warning(
                "[migrate_delegation_services_manually] Type de service destination '%s' non trouvé pour le service '%s', ignoré",
                new_kind_value,
                slug,
            )
            continue

        service.kinds.remove(delegation_kind)
        if new_kind not in service.kinds.all():
            service.kinds.add(new_kind)

        count_migrated += 1
        logger.info(
            "[migrate_delegation_services_manually] Migré le service '%s' de 'delegation' vers '%s'",
            slug,
            new_kind_value,
        )

    logger.info(
        "[migrate_delegation_services_manually] Migration terminée: %s migré(s), %s non trouvé(s), %s sans 'delegation'",
        count_migrated,
        count_not_found,
        count_no_delegation,
    )

    delegation_kind.delete()
    logger.info("[migrate_delegation_kind] Supprimé 'delegation'")


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0134_migrate_fee_conditions"),
    ]

    operations = [
        migrations.RunPython(
            migrate_service_kinds, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            migrate_delegation_kind,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
