# Generated by Django 6.0.1 on 2026-02-04 15:02

from django.db import migrations
from django.utils import timezone

DIFFUSION_ZONE_DEPARTMENT = "department"
DIFFUSION_ZONE_EPCI = "epci"
DIFFUSION_ZONE_CITY = "city"

SAINT_MARTIN_DEPARTMENT_CODE = "978"
SAINT_MARTIN_CITY_CODE = "97801"

EPT_CODES = {
    "200057867",  # Plaine commune
    "200057875",  # Est ensemble
    "200057941",  # Paris Est Marne et Bois
    "200057966",  # Vallée Sud-Grand Paris
    "200057974",  # Grand Paris Seine Ouest
    "200057982",  # Paris Ouest La Défense
    "200057990",  # Boucle Nord de Seine
    "200058006",  # Grand Paris Sud-Est Avenir
    "200058014",  # Grand-Orly Seine Bièvre
    "200058097",  # Paris Terres d'Envol
    "200058790",  # Grand Paris Grand Est
}
EPCI_CODE_FOR_EPT = "200054781"  # Métropole du Grand Paris
EPCI_CODE_MAPPING = {
    "200067221": "200096683",  # CC Centre Morbihan Communauté → CC Centre Morbihan Communauté
    "200071157": "200096634",  # CC des Hautes Vosges → CC des Hautes Vosges
    "200035459": "200096956",  # CA d'Agen → CA Agglomération d'Agen
    "200036572": "200096956",  # CC Porte d'Aquitaine en Pays de Serres → CA Agglomération d'Agen
}

CITY_CODE_MAPPING = {
    "93059": "93066",  # Pierrefitte-sur-Seine → Saint-Denis
    "62549": "62447",  # Marconne → Hesdin-la-Forêt
}


def migrate_departmental_diffusion_zone(services_to_update, department_code):
    if department_code == SAINT_MARTIN_DEPARTMENT_CODE:
        services_to_update.update(
            diffusion_zone_type=DIFFUSION_ZONE_CITY,
            diffusion_zone_details=SAINT_MARTIN_CITY_CODE,
            modification_date=timezone.now(),
        )


def migrate_epci_diffusion_zone(services_to_update, epci_code):
    if epci_code in EPT_CODES:
        new_epci_code = EPCI_CODE_FOR_EPT
    elif epci_code in EPCI_CODE_MAPPING:
        new_epci_code = EPCI_CODE_MAPPING[epci_code]
    else:
        return

    services_to_update.update(
        diffusion_zone_details=new_epci_code,
        modification_date=timezone.now(),
    )


def migrate_city_diffusion_zone(services_to_update, city_code):
    if city_code not in CITY_CODE_MAPPING:
        return

    services_to_update.update(
        diffusion_zone_details=CITY_CODE_MAPPING[city_code],
        modification_date=timezone.now(),
    )


def migrate_diffusion_zones(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    AE_Department = apps.get_model("admin_express", "Department")
    DA_Department = apps.get_model("decoupage_administratif", "Department")
    AE_EPCI = apps.get_model("admin_express", "EPCI")
    DA_EPCI = apps.get_model("decoupage_administratif", "EPCI")
    AE_City = apps.get_model("admin_express", "City")
    DA_City = apps.get_model("decoupage_administratif", "City")

    for diffusion_zone_type, AE_Model, DA_Model in [
        (DIFFUSION_ZONE_DEPARTMENT, AE_Department, DA_Department),
        (DIFFUSION_ZONE_EPCI, AE_EPCI, DA_EPCI),
        (DIFFUSION_ZONE_CITY, AE_City, DA_City),
    ]:
        lost_entity_codes = AE_Model.objects.exclude(
            code__in=DA_Model.objects.values("code")
        ).values_list("code", flat=True)
        for entity_code in lost_entity_codes:
            services_to_update = Service._base_manager.filter(
                diffusion_zone_type=diffusion_zone_type,
                diffusion_zone_details=entity_code,
            )
            if diffusion_zone_type == DIFFUSION_ZONE_DEPARTMENT:
                migrate_departmental_diffusion_zone(services_to_update, entity_code)
            elif diffusion_zone_type == DIFFUSION_ZONE_EPCI:
                migrate_epci_diffusion_zone(services_to_update, entity_code)
            elif diffusion_zone_type == DIFFUSION_ZONE_CITY:
                migrate_city_diffusion_zone(services_to_update, entity_code)


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0135_migrate_service_kinds"),
    ]

    operations = [
        migrations.RunPython(
            migrate_diffusion_zones, reverse_code=migrations.RunPython.noop
        )
    ]
