# Generated by Django 5.2.7 on 2025-11-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=5, unique=True)),
                ("code_departement", models.CharField(max_length=3)),
                ("code_epci", models.CharField(max_length=9)),
                ("code_region", models.CharField(max_length=3)),
                ("codes_postaux", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "commune",
                "verbose_name_plural": "communes",
            },
        ),
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=3, unique=True)),
                ("code_region", models.CharField(max_length=3)),
            ],
            options={
                "verbose_name": "département",
                "verbose_name_plural": "départements",
            },
        ),
        migrations.CreateModel(
            name="Epci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=9, unique=True)),
                ("codes_departements", models.JSONField(default=list)),
                ("codes_regions", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "EPCI",
                "verbose_name_plural": "EPCI",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=3, unique=True)),
            ],
            options={
                "verbose_name": "région",
                "verbose_name_plural": "régions",
            },
        ),
    ]
