# Generated by Django 5.2.9 on 2026-01-19 16:30
#
# Convertit les champs JSONField en ArrayField.
# Les données existantes seront supprimées car PostgreSQL ne peut pas
# convertir directement JSONB en array. Réimporter avec :
# python manage.py import_decoupage_administratif

import django.contrib.postgres.fields
from django.db import migrations, models


def truncate_tables(apps, schema_editor):
    """Vide les tables avant la conversion JSONField -> ArrayField."""
    schema_editor.execute("TRUNCATE TABLE decoupage_administratif_commune CASCADE;")
    schema_editor.execute("TRUNCATE TABLE decoupage_administratif_epci CASCADE;")


class Migration(migrations.Migration):
    dependencies = [
        ("decoupage_administratif", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(truncate_tables, migrations.RunPython.noop),
        # Commune: supprimer et recréer codes_postaux
        migrations.RemoveField(
            model_name="commune",
            name="codes_postaux",
        ),
        migrations.AddField(
            model_name="commune",
            name="codes_postaux",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=5),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        # Epci: supprimer et recréer codes_departements
        migrations.RemoveField(
            model_name="epci",
            name="codes_departements",
        ),
        migrations.AddField(
            model_name="epci",
            name="codes_departements",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=3),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        # Epci: supprimer et recréer codes_regions
        migrations.RemoveField(
            model_name="epci",
            name="codes_regions",
        ),
        migrations.AddField(
            model_name="epci",
            name="codes_regions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=3),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
