# Generated by Django 5.2.9 on 2026-01-19 16:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("decoupage_administratif", "0002_use_arrayfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=5, unique=True)),
                ("department", models.CharField(max_length=3)),
                ("epci", models.CharField(max_length=9)),
                ("region", models.CharField(max_length=3)),
                (
                    "postal_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=5),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "commune",
                "verbose_name_plural": "communes",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=3, unique=True)),
                ("region", models.CharField(max_length=3)),
            ],
            options={
                "verbose_name": "département",
                "verbose_name_plural": "départements",
            },
        ),
        migrations.DeleteModel(
            name="Commune",
        ),
        migrations.DeleteModel(
            name="Departement",
        ),
        migrations.RenameField(
            model_name="epci",
            old_name="codes_departements",
            new_name="departments",
        ),
        migrations.RenameField(
            model_name="epci",
            old_name="nom",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="epci",
            old_name="codes_regions",
            new_name="regions",
        ),
        migrations.RenameField(
            model_name="region",
            old_name="nom",
            new_name="name",
        ),
    ]
