# Generated by Django 5.2.9 on 2026-01-19 16:47

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("decoupage_administratif", "0003_rename_to_english"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="center",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="normalized_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="city",
            name="population",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="department",
            name="normalized_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="epci",
            name="normalized_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="region",
            name="normalized_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="city",
            name="department",
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name="city",
            name="epci",
            field=models.CharField(db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name="city",
            name="region",
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name="department",
            name="region",
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AddIndex(
            model_name="city",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["normalized_name"],
                name="da_city_name_trgm_idx",
                opclasses=("gin_trgm_ops",),
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["normalized_name"],
                name="da_dept_name_trgm_idx",
                opclasses=("gin_trgm_ops",),
            ),
        ),
        migrations.AddIndex(
            model_name="epci",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["normalized_name"],
                name="da_epci_name_trgm_idx",
                opclasses=("gin_trgm_ops",),
            ),
        ),
        migrations.AddIndex(
            model_name="region",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["normalized_name"],
                name="da_region_name_trgm_idx",
                opclasses=("gin_trgm_ops",),
            ),
        ),
    ]
