# Generated by Django 5.2.9 on 2026-01-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("decoupage_administratif", "0004_add_fields_and_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="id",
        ),
        migrations.RemoveField(
            model_name="department",
            name="id",
        ),
        migrations.RemoveField(
            model_name="epci",
            name="id",
        ),
        migrations.RemoveField(
            model_name="region",
            name="id",
        ),
        migrations.AlterField(
            model_name="city",
            name="code",
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="epci",
            name="code",
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="region",
            name="code",
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
