# Generated by Django 6.0.1 on 2026-01-28 15:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("decoupage_administratif", "0005_use_code_as_primary_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="center",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, srid=4326
            ),
        ),
    ]
