# Generated by Django 6.0.2 on 2026-03-02 14:46

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Establishment",
            fields=[
                (
                    "siret",
                    models.CharField(
                        max_length=14,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Siret",
                    ),
                ),
                (
                    "siren",
                    models.CharField(db_index=True, max_length=9, verbose_name="Siren"),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=255, verbose_name="Nom"),
                ),
                (
                    "parent_name",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="Nom de l’unité légale",
                    ),
                ),
                ("ape", models.CharField(max_length=6)),
                ("address1", models.CharField(max_length=255)),
                ("address2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("city_code", models.CharField(db_index=True, max_length=5)),
                ("postal_code", models.CharField(max_length=5)),
                ("is_siege", models.BooleanField(db_index=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                (
                    "full_search_text",
                    models.TextField(help_text="Renseigner NOM + NOM UNITÉ LÉGALE"),
                ),
            ],
            options={
                "verbose_name": "Établissement",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["full_search_text"],
                        name="full_text_trgm_idx",
                        opclasses=("gin_trgm_ops",),
                    )
                ],
            },
        ),
    ]
