# Generated by Django 6.0.2 on 2026-03-02 14:46

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import itoutils.django.nexus.models
from django.conf import settings
from django.db import migrations, models

import dora.core.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "sub_pc",
                    models.UUIDField(null=True, verbose_name="Identifiant ProConnect"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="Nom de famille"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=140, verbose_name="Prénom"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this user's email address has been validated.",
                        verbose_name="valid",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_manager",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si l’utilisateur est un gestionnaire (de département)",
                        verbose_name="gestionnaire",
                    ),
                ),
                (
                    "departments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=3),
                        blank=True,
                        help_text="Liste des numéros des départements gérés par l'utilisateur (s’il est gestionnaire). Séparés par des virgules.",
                        null=True,
                        verbose_name="Départements en gestion",
                    ),
                ),
                (
                    "main_activity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accompagnateur", "Accompagnateur"),
                            ("offreur", "Offreur"),
                            ("accompagnateur_offreur", "Accompagnateur et offreur"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Activité principale de l'utilisateur",
                    ),
                ),
                (
                    "discovery_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "bouche-a-oreille",
                                "Bouche-à-oreille (mes collègues, réseau, etc.)",
                            ),
                            (
                                "moteurs-de-recherche",
                                "Moteurs de recherche (Ecosia, Qwant, Google, Bing, etc.)",
                            ),
                            (
                                "reseaux-sociaux",
                                "Réseaux sociaux (Linkedin, Twitter, etc.)",
                            ),
                            (
                                "evenements-dora",
                                "Événements DORA (démonstration, webinaires, open labs, etc.)",
                            ),
                            ("autre", "Autre (préciser)"),
                        ],
                        max_length=25,
                        null=True,
                        verbose_name="comment avez-vous connu DORA\u202f?",
                    ),
                ),
                (
                    "discovery_method_other",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="comment avez-vous connu DORA\u202f? (autre)",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "last_service_reminder_email_sent",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("newsletter", models.BooleanField(db_index=True, default=False)),
                ("cgu_versions_accepted", models.JSONField(default=dict)),
                (
                    "bookmarks",
                    models.ManyToManyField(
                        through="services.Bookmark", to="services.service"
                    ),
                ),
            ],
            options={
                "verbose_name": "utilisateur",
                "verbose_name_plural": "utilisateurs",
                "abstract": False,
            },
            bases=(itoutils.django.nexus.models.NexusModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "anonymous_user_hash",
                    models.CharField(
                        help_text="userHash du localStorage pour les utilisateurs",
                        verbose_name="Identifiant anonyme",
                    ),
                ),
                (
                    "consent_version",
                    models.CharField(
                        help_text="Version de la politique de consentement présentée à l'utilisateur",
                        validators=[dora.core.validators.validate_version],
                        verbose_name="Version du consentement",
                    ),
                ),
                (
                    "consent_choices",
                    models.JSONField(
                        default=dict,
                        help_text="Statut de consentement pour chaque service",
                        verbose_name="Services consentis",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Date et heure du consentement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consent_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enregistrement de consentement",
                "verbose_name_plural": "Enregistrements de consentement",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="users_conse_user_id_9b8797_idx",
                    ),
                    models.Index(
                        fields=["anonymous_user_hash", "-created_at"],
                        name="users_conse_anonymo_f95d1c_idx",
                    ),
                ],
            },
        ),
    ]
