# Generated by Django 4.2.17 on 2025-01-28 14:44

from django.db import migrations


def normalize_emails(apps, schema_editor):
    User = apps.get_model("users", "User")

    for user in User.objects.all():
        normalized_email = user.email.lower()
        User.objects.filter(pk=user.pk).update(email=normalized_email)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0029_user_sub_pc"),
    ]

    operations = [
        migrations.RunPython(normalize_emails),
    ]
