# Generated by Django 5.2.3 on 2025-06-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_normalize_emails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="ic_id",
        ),
    ]
