# Generated by Django 5.2.6 on 2025-10-22 14:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_remove_user_ic_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("anonymous_id", models.CharField(blank=True, help_text="userHash du localStorage pour les utilisateurs anonymes", null=True, verbose_name="Identifiant anonyme")),
                ("consent_version", models.CharField(help_text="Version de la politique de consentement présentée à l'utilisateur", max_length=10, verbose_name="Version du consentement")),
                ("consent_choices", models.JSONField(default=dict, help_text="Statut de consentement pour chaque service", verbose_name="Services consentis")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date et heure du consentement")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="consent_records", to=settings.AUTH_USER_MODEL, verbose_name="Utilisateur")),
            ],
            options={
                "verbose_name": "Enregistrement de consentement",
                "verbose_name_plural": "Enregistrements de consentement",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["user", "-created_at"], name="users_conse_user_id_9b8797_idx"), models.Index(fields=["anonymous_id", "-created_at"], name="users_conse_anonymo_d7875c_idx")],
                "constraints": [models.CheckConstraint(condition=models.Q(models.Q(("anonymous_id__isnull", True), ("user__isnull", False)), models.Q(("anonymous_id__isnull", False), ("user__isnull", True)), _connector="OR"), name="soit_utilisateur_soit_anonyme")],
            },
        ),
    ]
