# Generated by Django 6.0.2 on 2026-02-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0032_consentrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="discovery_method",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "bouche-a-oreille",
                        "Bouche-à-oreille (mes collègues, réseau, etc.)",
                    ),
                    (
                        "moteurs-de-recherche",
                        "Moteurs de recherche (Ecosia, Qwant, Google, Bing, etc.)",
                    ),
                    ("reseaux-sociaux", "Réseaux sociaux (Linkedin, Twitter, etc.)"),
                    (
                        "evenements-dora",
                        "Événements DORA (démonstration, webinaires, open labs, etc.)",
                    ),
                    ("emplois-de-l-inclusion", "Emplois de l'inclusion"),
                    ("autre", "Autre (préciser)"),
                ],
                max_length=25,
                null=True,
                verbose_name="comment avez-vous connu DORA\u202f?",
            ),
        ),
    ]
