# Generated by Django 6.0.2 on 2026-03-02 14:46

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models

import dora.orientations.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orientation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "query_expires_at",
                    models.DateTimeField(
                        default=dora.orientations.models._orientation_query_expiration_date,
                        verbose_name="expiration du lien de la demande",
                    ),
                ),
                (
                    "requirements",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=480),
                        blank=True,
                        default=list,
                        verbose_name="Critères",
                    ),
                ),
                (
                    "situation",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=480),
                        blank=True,
                        default=list,
                        verbose_name="Situation",
                    ),
                ),
                (
                    "situation_other",
                    models.CharField(
                        blank=True, max_length=480, verbose_name="Situation - autre"
                    ),
                ),
                (
                    "beneficiary_france_travail_number",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="Numéro France Travail"
                    ),
                ),
                (
                    "beneficiary_last_name",
                    models.CharField(max_length=140, verbose_name="Nom bénéficiaire"),
                ),
                (
                    "beneficiary_first_name",
                    models.CharField(
                        max_length=140, verbose_name="Prénom bénéficiaire"
                    ),
                ),
                (
                    "beneficiary_contact_preferences",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("TELEPHONE", "Téléphone"),
                                ("EMAIL", "E-mail"),
                                ("REFERENT", "Via le conseiller référent"),
                                ("AUTRE", "Autre"),
                            ],
                            max_length=10,
                        ),
                        default=list,
                        verbose_name="Préférences de contact",
                    ),
                ),
                (
                    "beneficiary_phone",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Tel bénéficiaire"
                    ),
                ),
                (
                    "beneficiary_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Courriel bénéficiaire"
                    ),
                ),
                (
                    "beneficiary_other_contact_method",
                    models.CharField(
                        blank=True,
                        max_length=280,
                        verbose_name="Autre méthode de contact bénéficiaire",
                    ),
                ),
                (
                    "beneficiary_availability",
                    models.DateField(
                        blank=True, null=True, verbose_name="Disponibilité bénéficiaire"
                    ),
                ),
                (
                    "beneficiary_attachments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1024),
                        blank=True,
                        default=list,
                        verbose_name="Documents joints",
                    ),
                ),
                (
                    "referent_last_name",
                    models.CharField(max_length=140, verbose_name="Nom référent"),
                ),
                (
                    "referent_first_name",
                    models.CharField(max_length=140, verbose_name="Prénom référent"),
                ),
                (
                    "referent_phone",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Tel référent"
                    ),
                ),
                (
                    "referent_email",
                    models.EmailField(max_length=254, verbose_name="Courriel référent"),
                ),
                (
                    "duration_weekly_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre d'heures par semaine pour effectuer ce service",
                        null=True,
                        verbose_name="Nombre d'heures par semaine",
                    ),
                ),
                (
                    "duration_weeks",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre de semaines que durent le service",
                        null=True,
                        verbose_name="Nombre de semaines",
                    ),
                ),
                ("di_service_id", models.TextField(blank=True, default="")),
                ("di_service_name", models.TextField(blank=True, default="")),
                ("di_service_address_line", models.TextField(blank=True, default="")),
                ("di_contact_email", models.TextField(blank=True, default="")),
                ("di_contact_name", models.TextField(blank=True, default="")),
                ("di_contact_phone", models.TextField(blank=True, default="")),
                ("di_structure_name", models.TextField(blank=True, default="")),
                (
                    "data_protection_commitment",
                    models.BooleanField(
                        default=False, verbose_name="Engagement RGPD accompagnateur"
                    ),
                ),
                (
                    "original_service_name",
                    models.CharField(
                        default="",
                        editable=False,
                        max_length=140,
                        verbose_name="Nom original",
                    ),
                ),
                (
                    "orientation_reasons",
                    models.TextField(blank=True, verbose_name="Motif de l'orientation"),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "processing_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de traitement"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MODÉRATION_EN_COURS", "En cours de modération"),
                            ("MODÉRATION_REJETÉE", "Rejetée par la modération"),
                            ("OUVERTE", "Ouverte / En cours de traitement"),
                            ("VALIDÉE", "Validée"),
                            ("REFUSÉE", "Refusée"),
                            ("EXPIRÉE", "Expirée"),
                        ],
                        default="OUVERTE",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "last_reminder_email_sent",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "is_anonymized",
                    models.BooleanField(
                        default=False, verbose_name="Orientation anonymisée"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RejectionReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Motif de refus",
                "verbose_name_plural": "Motifs de refus",
            },
        ),
        migrations.CreateModel(
            name="SentContactEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_sent", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.CharField(
                        choices=[
                            ("BÉNÉFICIAIRE", "Bénéficiaire"),
                            ("PRESCRIPTEUR", "Prescripteur"),
                            ("RÉFÉRENT", "Référent"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "carbon_copies",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("BÉNÉFICIAIRE", "Bénéficiaire"),
                                ("PRESCRIPTEUR", "Prescripteur"),
                                ("RÉFÉRENT", "Référent"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                        verbose_name="Carbon Copies",
                    ),
                ),
            ],
        ),
    ]
