# Generated by Django 6.0.2 on 2026-03-02 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orientations", "0001_initial"),
        ("services", "0001_initial"),
        ("structures", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orientation",
            name="prescriber",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Prescripteur",
            ),
        ),
        migrations.AddField(
            model_name="orientation",
            name="prescriber_structure",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orientations",
                to="structures.structure",
                verbose_name="Structure",
            ),
        ),
        migrations.AddField(
            model_name="orientation",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="services.service",
                verbose_name="Service",
            ),
        ),
        migrations.AddField(
            model_name="orientation",
            name="rejection_reasons",
            field=models.ManyToManyField(
                blank=True,
                to="orientations.rejectionreason",
                verbose_name="Motifs de refus de l'orientation",
            ),
        ),
        migrations.AddField(
            model_name="sentcontactemail",
            name="orientation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orientations.orientation",
            ),
        ),
        migrations.AddConstraint(
            model_name="orientation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("service", None),
                        models.Q(("di_service_id", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("service", None), _negated=True),
                        ("di_service_id", ""),
                    ),
                    _connector="OR",
                ),
                name="check_valid_service",
            ),
        ),
    ]
