# Generated by Django 6.0.2 on 2026-03-13 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0003_orientation_les_emplois_beneficiary_uid_and_more"),
        ("services", "0003_seed_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orientation",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orientations",
                to="services.service",
                verbose_name="Service",
            ),
        ),
    ]
