# Generated by Django 6.0.4 on 2026-05-12 14:23

from django.db import migrations, models

import dora.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0004_add_service_orientations_related_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientation",
            name="is_from_les_emplois",
            field=models.BooleanField(
                default=False, verbose_name="Orientation venant des Emplois"
            ),
        ),
        migrations.AddField(
            model_name="orientation",
            name="les_emplois_prescriber_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Les Emplois - Email prescripteur",
            ),
        ),
        migrations.AddField(
            model_name="orientation",
            name="les_emplois_prescriber_first_name",
            field=models.CharField(
                blank=True,
                max_length=140,
                null=True,
                verbose_name="Les Emplois - Prénom prescripteur",
            ),
        ),
        migrations.AddField(
            model_name="orientation",
            name="les_emplois_prescriber_id",
            field=models.UUIDField(
                blank=True,
                null=True,
                verbose_name="Les Emplois - Identifiant prescripteur",
            ),
        ),
        migrations.AddField(
            model_name="orientation",
            name="les_emplois_prescriber_last_name",
            field=models.CharField(
                blank=True,
                max_length=140,
                null=True,
                verbose_name="Les Emplois - Nom prescripteur",
            ),
        ),
        migrations.AddField(
            model_name="orientation",
            name="les_emplois_prescriber_phone",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Les Emplois - Téléphone prescripteur",
            ),
        ),
        migrations.AddField(
            model_name="orientation",
            name="les_emplois_structure_name",
            field=models.CharField(
                blank=True,
                max_length=140,
                null=True,
                verbose_name="Les Emplois - Nom structure",
            ),
        ),
        migrations.AddField(
            model_name="orientation",
            name="les_emplois_structure_siret",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                validators=[dora.core.validators.validate_siret],
                verbose_name="Les Emplois - SIRET structure",
            ),
        ),
        migrations.AlterField(
            model_name="orientation",
            name="les_emplois_beneficiary_id",
            field=models.UUIDField(
                blank=True,
                null=True,
                verbose_name="Les Emplois - Identifiant bénéficiaire",
            ),
        ),
        migrations.AlterField(
            model_name="orientation",
            name="les_emplois_structure_id",
            field=models.UUIDField(
                blank=True,
                null=True,
                verbose_name="Les Emplois - Identifiant structure",
            ),
        ),
    ]
