# Generated by Django 6.0.5 on 2026-05-15 17:53

import django.db.models.deletion
from django.db import migrations, models

import dora.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0004_add_service_orientations_related_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmploisOrientationData",
            fields=[
                (
                    "orientation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="emplois_orientation_data",
                        serialize=False,
                        to="orientations.orientation",
                        verbose_name="Orientation",
                    ),
                ),
                (
                    "beneficiary_id",
                    models.UUIDField(verbose_name="Identifiant bénéficiaire"),
                ),
                (
                    "structure_id",
                    models.UUIDField(verbose_name="Identifiant structure"),
                ),
                (
                    "structure_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=140,
                        verbose_name="Nom structure",
                    ),
                ),
                (
                    "structure_siret",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=14,
                        validators=[dora.core.validators.validate_siret],
                        verbose_name="SIRET structure",
                    ),
                ),
                (
                    "prescriber_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Identifiant prescripteur"
                    ),
                ),
                (
                    "prescriber_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="Email prescripteur",
                    ),
                ),
                (
                    "prescriber_first_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=140,
                        verbose_name="Prénom prescripteur",
                    ),
                ),
                (
                    "prescriber_last_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=140,
                        verbose_name="Nom prescripteur",
                    ),
                ),
                (
                    "prescriber_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Téléphone prescripteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Données Les Emplois",
                "verbose_name_plural": "Données Les Emplois",
            },
        ),
        migrations.RemoveField(
            model_name="orientation",
            name="les_emplois_beneficiary_id",
        ),
        migrations.RemoveField(
            model_name="orientation",
            name="les_emplois_structure_id",
        ),
    ]
