# Generated by Django 6.0.6 on 2026-07-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0005_emploisorientationdata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emploisorientationdata",
            name="emplois_sync_uid",
            field=models.UUIDField(null=True, verbose_name="Emplois sync UID"),
        ),
    ]
