# Generated by Django 6.0.6 on 2026-07-07 10:46
import uuid

from django.db import migrations, models


def backfill_unique_uuids(apps, schema_editor):
    EmploisOrientationData = apps.get_model("orientations", "EmploisOrientationData")
    rows = list(
        EmploisOrientationData.objects.filter(emplois_sync_uid__isnull=True).only("pk")
    )
    for row in rows:
        row.emplois_sync_uid = uuid.uuid4()
    if rows:
        EmploisOrientationData.objects.bulk_update(rows, ["emplois_sync_uid"])


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0005_emploisorientationdata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emploisorientationdata",
            name="emplois_sync_uid",
            field=models.UUIDField(null=True, verbose_name="Emplois sync UID"),
        ),
        migrations.RunPython(backfill_unique_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="emploisorientationdata",
            name="emplois_sync_uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                null=False,
                verbose_name="Emplois sync UID",
            ),
        ),
    ]
