# Generated by Django 6.0.8 on 2026-09-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0006_emploisorientationdata_emplois_sync_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orientation",
            name="status",
            field=models.CharField(
                choices=[
                    ("MODÉRATION_EN_COURS", "En cours de modération"),
                    ("MODÉRATION_REJETÉE", "Rejetée par la modération"),
                    ("OUVERTE", "En cours de traitement"),
                    ("VALIDÉE", "Validée"),
                    ("REFUSÉE", "Déclinée"),
                    ("EXPIRÉE", "Expirée"),
                ],
                default="OUVERTE",
                max_length=20,
                verbose_name="statut",
            ),
        ),
    ]
