# Generated by Django 6.0.8 on 2026-09-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0007_alter_orientation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orientation",
            name="original_service_name",
            field=models.CharField(
                default="", editable=False, max_length=150, verbose_name="Nom original"
            ),
        ),
    ]
