# Generated by Django 4.2.16 on 2024-12-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0010_orientation_check_valid_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orientation",
            name="status",
            field=models.CharField(
                choices=[
                    ("MODERATION_PENDING", "En cours de modération"),
                    ("MODERATION_REJECTED", "Rejetée par la modération"),
                    ("OUVERTE", "Ouverte / En cours de traitement"),
                    ("VALIDÉE", "Validée"),
                    ("REFUSÉE", "Refusée"),
                ],
                default="OUVERTE",
                max_length=20,
                verbose_name="statut",
            ),
        ),
    ]
