# Generated by Django 4.2.16 on 2024-12-12 10:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0010_orientation_check_valid_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orientation",
            name="beneficiary_contact_preferences",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("TELEPHONE", "Téléphone"),
                        ("EMAIL", "E-mail"),
                        ("REFERENT", "Via le conseiller référent"),
                        ("AUTRE", "Autre"),
                    ],
                    max_length=10,
                ),
                default=list,
                size=None,
                verbose_name="Préférences de contact",
            ),
        ),
    ]
