# Generated by Django 4.2.16 on 2024-12-10 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0072_alter_structure_name"),
        ("orientations", "0012_alter_orientation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orientation",
            name="prescriber_structure",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orientations",
                to="structures.structure",
                verbose_name="Structure",
            ),
        ),
    ]
