# Generated by Django 4.2.17 on 2025-01-23 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0115_service_update_frequency"),
        ("orientations", "0013_alter_orientation_prescriber_structure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orientation",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="services.service",
                verbose_name="Service",
            ),
        ),
    ]
