# Generated by Django 4.2.17 on 2025-01-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0014_alter_orientation_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientation",
            name="di_service_address_line",
            field=models.TextField(blank=True, default=""),
        ),
    ]
