# Generated by Django 4.2.17 on 2025-01-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0015_orientation_di_service_address_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientation",
            name="duration_weekly_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Nombre d'heures par semaine pour effectuer ce service",
                null=True,
                verbose_name="Nombre d'heures par semaine",
            ),
        ),
        migrations.AddField(
            model_name="orientation",
            name="duration_weeks",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Nombre de semaines que durent le service",
                null=True,
                verbose_name="Nombre de semaines",
            ),
        ),
    ]
