# Generated by Django 5.2.4 on 2025-08-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0016_orientation_duration_weekly_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientation",
            name="beneficiary_france_travail_number",
            field=models.CharField(
                blank=True, max_length=11, verbose_name="Numéro France Travail"
            ),
        ),
    ]
