# Generated by Django 5.2.4 on 2025-08-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0017_orientation_beneficiary_france_travail_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientation",
            name="data_protection_commitment",
            field=models.BooleanField(
                default=False, verbose_name="Engagement RGPD accompagnateur"
            ),
        ),
    ]
