# Generated by Django 5.2.8 on 2025-12-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0018_orientation_data_protection_commitment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orientation",
            name="status",
            field=models.CharField(
                choices=[
                    ("MODÉRATION_EN_COURS", "En cours de modération"),
                    ("MODÉRATION_REJETÉE", "Rejetée par la modération"),
                    ("OUVERTE", "Ouverte / En cours de traitement"),
                    ("VALIDÉE", "Validée"),
                    ("REFUSÉE", "Refusée"),
                    ("EXPIRÉE", "Expirée"),
                ],
                default="OUVERTE",
                max_length=20,
                verbose_name="statut",
            ),
        ),
    ]
