# Generated by Django 5.2.9 on 2026-01-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0019_alter_orientation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientation",
            name="is_anonymized",
            field=models.BooleanField(
                default=False, verbose_name="Orientation anonymisée"
            ),
        ),
    ]
