# Generated by Django 6.0.2 on 2026-02-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0020_orientation_is_anonymized"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientation",
            name="les_emplois_beneficiary_uid",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="UID bénéficiaire Les Emplois"
            ),
        ),
        migrations.AddField(
            model_name="orientation",
            name="les_emplois_structure_uid",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="UID structure Les Emplois"
            ),
        ),
    ]
