name: Création des review apps

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Numéro de la PR'
        required: true
        type: string

jobs:
  create-review-apps:
    runs-on: ubuntu-latest
    steps:
      - name: Installation de Scalingo CLI
        uses: scalingo-community/setup-scalingo@v0.1.1
        with:
          region: 'osc-fr1'
          api_token: ${{ secrets.SCALINGO_CLI_TOKEN }}

      - name: Création des review apps
        run: |
          chmod +x ./tools/create-review-apps.sh
          ./tools/create-review-apps.sh ${{ github.event.inputs.pr_number }}
