name: Dora Front CI

permissions:
  contents: read

on:
  push:
    paths:
      - 'front/**'
      - '.github/workflows/front-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.13]

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: front
        run: npm install

      - name: Check formatting
        working-directory: front
        run: npm run format:check

      - name: Lint code
        working-directory: front
        run: npm run lint

      - name: Run tests
        working-directory: front
        run: npm run test
